### ISSUE TITLE
Reproduction Phenology

### ISSUE THREAD

**Issue by crollinson** [EDmodel/ED2#112]
Unless I'm mistaken, reproduction currently occurs in every month, regardless of phenology, unless the plant_min_temp threshold is crossed.  plant_min_temp is also tied to mortality and is a threshold that (at least in my runs) is rarely crossed.  Towards the end of the reproduction code, pheninit_balive_bstorage is called (phenology_aux.f90), but it only really deals with setting the phenology of drought-deciduous species.   

It seems to me that a logical thing to do is to condition allow_pft at the beginning of reproduction on PFT-specific phenology rather than a straight min temp.  Seems like it _should_ be a fairly straightforward fix, but I'm welcome to suggestions of why this is a bad idea.

**Comment by mdietze** [comment]
I think you're mistaken. Allocation to both reproduction and structural growth only occurs when 

if ((phenology(ipft) /= 2   .or.  late_spring) .and. phen_status == 0) 

https://github.com/EDmodel/ED2/blob/master/ED/src/dynamics/structural_growth.f90#L921

**Comment by crollinson** [comment]
*Allocation* to reproduction only happens when things are leafed out and on June 1, but the actual process of seedling establishment happens for all PFTs every month -- even January -- because seed rain is independent of reproduction biomass.   (I just ran through a short bare ground spin with print statement to confirm this.)

**Comment by mdietze** [comment]
Yes, I see your point, but in general that input should be very small. Unless I'm starting from bare ground I typically set it to 0.
