### ISSUE TITLE
Clarification about NL%EDGEOFF [RAPP]

### ISSUE THREAD

**Issue by fabeuw** [EDmodel/ED2#116]
I am wondering what NL%EDGEOFF actually represents, is it the number of cells or degrees?
In other words if I have 
NL%LONW =   0.    ! Westermost   longitude allowed to be included;
 NL%LONE =   32.    ! Easternmost  longitude allowed to be included;
 NL%LATS =  -22.    ! Southernmost latitude  allowed to be included;
 NL%LATN =   22.    ! Northernmost latitude  allowed to be included;

and NL%EDGEOFF set to 5, will my data be usable only in the grid 5,27,-17,17? 
I want to process the smallest possible amount of data since I will be working in ED only with one point. Does this mean that if I plan to use data only in one grid cell I will have to make a "square" around if of 5 degrees/cells?

**Comment by mpaiao** [comment]
It's the number of cells.   You can probably make edgeoff smaller (2).

**Comment by fabeuw** [comment]
@mpaiao ok thanks I see how that works now. But why the are the h5 output grids not 2.5º? My lat look like this 5.625	7.5	9.375	11.25	13.125	15.0
and lon 0.952368 -0.952368 -2.8571 -4.76184  -6.66657 -8.57131 -10.47604
It's about 1.9º for lon and 1.825º grids for lat. I see that in ncep_coordinates.f90 there is a mention that RAPP does not support moving grids, not sure if that's related. This means that the original ncep grids interpolated and downscaled, what is the purpose of this? thanks

**Comment by mpaiao** [comment]
@fabeuw If I remember correctly, native NCEP reanalyses are not at 2.5°.  They use some Gaussian grid, which is probably closer to the 1.9/1.825...  If I remember correctly, the "readily available" data are at the NCEP website is at 2.5°, but if you go through the UCAR data servers you may be able to get the native grid.

I think the "moving grid" was just a weird way of saying that lon/lat shall not vary with time.

**Comment by fabeuw** [comment]
@mpaiao, just for the record I checked and actually the data that it's downloaded by RAPP from the NCAR server comes both in gaussian and non-gaussian grids depending on the variable. Perhaps most of the original data come from PSD, and data before 1957 are in non-gaussian grids. Thanks
