### ISSUE TITLE
short wave and downward long wave radiation

### ISSUE THREAD

**Issue by ashehad** [EDmodel/ED2#120]
Hi All,

When we construct the met forcing for ED, we constrain the short-wave radiation. The upper constrain for short-wave radiation is a function of zenith angle (in an implicit way). Do we constrain the long-wave radiation? If so, how do we decide the upper bound? Are these upper bounds site specific?

Thanks,
Ashehad

**Comment by mpaiao** [comment]
@ashehad Not sure if this is what you meant, but ED also checks the values of incoming longwave radiation.  The default acceptable range is quite broad right now, between 40 and 600 (look for rlong_min/rlong_max in ED/src/init/ed_params.f90). As a rule of thumb, you shouldn't expect incoming radiation to be much higher than 5.67E-8 * T(surface)^4  (T in Kelvin).   Values can be lower than this number, especially under cloud free and dry weather, and if your area of interest is at high elevation (though 40 is very low for most cases).

**Comment by ashehad** [comment]
@mpaiao Yup, kind of what I meant. Thanks for your input.
