### ISSUE TITLE
config.xml

### ISSUE THREAD

**Issue by ashehad** [EDmodel/ED2#123]
Hi All,

I'd like to know if there's an option in ED2IN such that every time I run the executable of ED, together with ED2IN and climate forcing, I get the config.xml.

Related to this issue is the state of the parameters that we have in the present version of ED. Is there a way to track the history of the parameter values?  

Best,
Ashehad

**Comment by apourmok** [comment]
If you are using the latest version of main line, you get that file in your
output folder.

**Comment by crollinson** [comment]
Just to expand a bit on Afshin's reply:
the .xml file with all of the user-specified settings (from ED2IN and any additional xml specifications) should get written to wherever your output folder is (i.e. whatever you set the path for in NL%SFILOUT in the ED2IN).  This was recently updated and should be pretty comprehensive. 

Anything not specified via ED2IN or XML (see ED/src/io/ed_xml_config.f90 for what can get read in) can be found in ED/src/init/ed_params.f90 or possibly the various "coms.f90" files depending on what you're looking for.  Any recent change in these default values should be visible through the github history.

**Comment by ashehad** [comment]
Thanks!
