### ISSUE TITLE
How to deal with HDF5 libraries - make file to install components to compile ED

### ISSUE THREAD

**Issue by fabeit** [EDmodel/ED2#125]
Hello!
I just had a frustrating afternoon doing a fresh install of ED on Ubuntu, I am sure other users had or will have problems with this. I am wondering how other people deal with the HDF5 libraries. There are precompiled ones https://www.hdfgroup.org/HDF5/release/obtain5.html or the source code. I have not been able to understand if the precompiled ones will work with ED because I ended up compiling my own with this command CC=/usr/bin/mpicc ./configure --enable-parallel --enable-fortran
But for future references what is the quickest way to properly install this library? I had to manually copy the compiled library into my /usr/include and /urs/bin folders. Do they need to be compiled with --enable-parallel? Actually when I tested the library it didn't pass the MPI test but it passed the other tests and then it worked with ED. I have written a make file that will almost automatically install everything necessary to compile ED, and I want to add this to the wiki but first I want to understand the situation with the HDF5.

**Comment by DanielNScott** [comment]
I have had some similar difficulties installing ED on a copy of Ubuntu (14.04) too. Would you share your makefile here for the time being? If I can find the time I'll look into this as well...

**Comment by fabeit** [comment]
[quick install ED ubuntu.txt](https://github.com/EDmodel/ED2/files/476877/quick.install.ED.ubuntu.txt)
with much delay, here it goes, if you want to use it for the wiki, in any case it's good to have something on record also for other people.

**Comment by xiangtao-princeton** [comment]
@fabeit  Thanks for the instruction! I'm closing this issue since it is resolved.
