### ISSUE TITLE
Issue with installation of ED2 on Mac OS X

### ISSUE THREAD

**Issue by manfredo89** [EDmodel/ED2#128]
Hello to everybody, 
I tried to follow the instructions for the installation but I continue running into these errors after ./install.sh. I have seen a similar post ( https://github.com/EDmodel/ED2/issues/7 ) but here the solution may be different. Thanks for any help.

Can't find file: string.h
Can't find file: utmpx.h
=== Finished dependencies ===
make /Users/manfredo/Desktop/ED2/ED/build//ed_2.1-opt
cp -f /Users/manfredo/Desktop/ED2/ED/src/init/ed_init.F90 ed_init.F90
mpif90 -c -DUSE_INTERF=1 -DUSENC=0 -DMAC_OS_X -DUSE_HDF5=1 -DUSE_COLLECTIVE_MPIO=0 -DUSE_MPIWTIME=0 -O3 -ffree-line-length-none  -I/Users/manfredo/Desktop/ED2/ED/src/include -I/usr/hdf5-1.8.7-mac-intel-x86_64-static/include   -DRAMS_MPI ed_init.F90
ed_init.F90:131.31:

         call soil_default_fill(cgrid,ifm,ipy)
                               1
Error: Explicit interface required for 'soil_default_fill' at (1): target argument
ed_init.F90:494.29:

         call print_soil_info(edgrid_g(igr),igr)
                             1
Error: Explicit interface required for 'print_soil_info' at (1): target argument
make[1]: *** [ed_init.o] Error 1
make: *** [all] Error 2

**Comment by DanielNScott** [comment]
I believe I have the same (original) issue when trying to use the gfortran compiler, but I'll make a note to double check that. Re. the ifort compilation, did you run install.sh clean first? I tend to run into errors like the one's you've just described when I forget to remove all the .o and .mod files that one compiler has created before attempting an install with a different compiler.

Sorry to see the installation's been a pain...

**Comment by manfredo89** [comment]
The compilation was run from scratch so there should't have been cleaning issues. I solved the problem, but really can not figure out what is happening. Apparently a bunch of object files were not appended to the archive library ed-2.1.a. Those are the following:

decomp_coms.o detailed_coms.o disturb_coms.o ed_misc_coms.o ed_node_coms.o ed_para_coms.o grid_coms.o hdf5_coms.o hydrology_coms.o mem_polygons.o optimiz_coms.o phenology_coms.o physiology_coms.o

manually linking against these solved all the errors but one. Indeed the utils_c.c file has also symbols that cause problems, in particular the findmycpu function which I simply commented (maybe the SUNHPC ifdef could be extended to __APPLE__)

    #include <utmpx.h>
    int sched_getcpu();
    int findmycpu_ ()
    {
        int cpu;
        cpu = sched_getcpu();
        return cpu;
    }
    #endif

**Comment by manfredo89** [comment]
Turned out to be the ar archive utility that (on Mac) does not add objects with common symbols to the library. Solved by using

    libtool -c -static -o

instead of 

    ar rs
I am pulling a request to merge the new include file for Mac.
