### ISSUE TITLE
CSS file size-structure script?

### ISSUE THREAD

**Issue by DanielNScott** [EDmodel/ED2#139]
Does anyone have a script for reading .css files and producing a size-and-pft structure graph?

I would like to look into how few cohorts I can get away with using in a simulation, so taking an approximately size-and-pft distribution preserving sub-sample of cohorts in a .css seems like a good place to start.

**Comment by mdietze** [comment]
Wouldn't varying MAXCOHORTS achieve the same ends with a lot less work (i.e. letting cohort fusion handle the process of combining cohorts while preserving the biomass distribution). I know that when we start from lots of cohorts (e.g. inventory data) but want to do faster runs this is how we combine them rather than doing any manual merge or subsample a priori

**Comment by DanielNScott** [comment]
Yeah, sort of. MAXPATCH, MAXCOHORT, etc do work with an existing initialization and try to merge things to comply with the numbers you provide, so they're aiming at the same thing. They don't force  merge things that are too-dissimilar though and they're a little bit opaque in the sense that I don't know exactly what the distribution looks like before and after unless I look at the model size and pft structure from the output.

I also don't know right now what sort of error they tolerate in terms of similarity, or equivalently how much resolution in the demographic structure they try to maintain. I know I can find these things out of course, but if someone's got a script which looks at .css files, I thought I'd start there.

**Comment by mpaiao** [comment]
@DanielNScott I have this script, not sure if this is what you're looking for...

[plot_pss+css.zip](https://github.com/EDmodel/ED2/files/51302/plot_pss.css.zip)

**Comment by DanielNScott** [comment]
seems like it! thanks!
