### ISSUE TITLE
Compile issues with latest re-org of ED dirs

### ISSUE THREAD

**Issue by serbinsh** [EDmodel/ED2#159]
I am not sure if this is similar to #153 but I am just getting to trying the latest version of ED2 git after the reorg.  I am now unable to compile with this error:

```
mpif90 -c -DUSE_INTERF=1 -DUSENC=0 -DPC_GFORTRAN -DUSE_HDF5=1 -DUSE_COLLECTIVE_MPIO=0 -DUSE_MPIWTIME=1 -g -ffree-line-length-none -fno-whole-file -O2 -fopenmp   -I../../src/include -I/usr/include   -DRAMS_MPI -I/usr/include hdf5_coms.F90
hdf5_coms.F90:3.7:

   use hdf5
       1
Fatal Error: Cannot read module file 'hdf5.mod' opened at (1), because it was created by a different version of GNU Fortran
make[1]: *** [hdf5_coms.o] Error 1
make[1]: Leaving directory `/data/sserbin/Modeling/ED2.git/ED/build/bin-opt-E-serbinsh-7b564a2'
make: *** [all] Error 2

```

However I have linked to the proper .opt file in /make

lrwxrwxrwx. 1 sserbin test    18 Apr 19 10:24 include.mk.opt -> include.mk.opt.bnl

What am I missing?

Also, is there no longer a ./install clean option?  I wasn't able to get it to work.  Apologies if I have missed something simple

**Comment by DanielNScott** [comment]
Hey Sean,

I described the changes I made in #155 and #156 but they were a little buried so I'm sorry for the difficulty. Maybe I should modify install.sh to accept ```--help``` too now that I think about it, it would only take a minute....

Anyway, the answer to your questions: 
- clean still exists, but per the rest of the changes it's in standard format, as ```install.sh --clean``` or ```install.sh -c``` if you want to type less.
- getting the proper include.mk file requires specifying a platform and a kind, i.e. ```install.sh --platform bnl --kind E``` for your case, or ```install.sh -p bnl```
- ```--platform``` flag defaults to ```gfortran``` and ```--kind``` defaults to ```E``` if either is not specified.

**Comment by DanielNScott** [comment]
I guess one more thing to note: I assumed people are generally using one compiler, so the build directories are not compiler tagged. Hence, if you build with ```install.sh -p odyssey``` and then try to use ```install.sh -p gfortran``` the gfortran compilation will not work (unless you change ```-k```) because it will attempt to use the same directory that's already been built in. In this case you need to run ```install.sh --clean```.

**Comment by ashiklom** [comment]
I can confirm the same problem as @serbinsh trying to compile latest git release of ED2 with `gfortran-4.7`:

```
/bin/rm -f hdf5_coms.F90
/bin/cp -f ../../src/memory/hdf5_coms.F90 hdf5_coms.F90
gfortran-4.7 -c -DUSE_INTERF=1 -DUSENC=0 -DPC_GFORTRAN -DUSE_HDF5=1 -DUSE_COLLECTIVE_MPIO=0 -DUSE_MPIWTIME=1 -g -ffree-line-length-none -O2 -fopenmp  -fno-whole-file   -I../../src/include -I/usr/include/mpich -I/usr/include/hdf5/mpich   -DRAMS_MPI -I/usr/include/mpich -I/usr/include/hdf5/mpich hdf5_coms.F90
hdf5_coms.F90:3.7:

   use hdf5
       1
Fatal Error: File 'hdf5.mod' opened at (1) is not a GFORTRAN module file
rules.mk:312: recipe for target 'hdf5_coms.o' failed
make[1]: *** [hdf5_coms.o] Error 1
make[1]: Leaving directory '/home/ashiklom/Projects/ED2/ED/build/bin-opt-E-radiation-refactor-7b564a2'
Makefile:51: recipe for target 'all' failed
make: *** [all] Error 2
```

I suspect it may have to do with the fact that I am compiling against newer `hdf5` libraries (they are the latest ones available in the default Ubuntu Software Repositories), while I had to get an older version of `gfortran` (current one is 5.2.1, the one I'm using is 4.7) that still has the depcrecated `-fno-whole-file` flag. I'll take a stab at installing older hdf5 libraries from source and seeing if that works...

**Comment by crollinson** [comment]
Can you guys confirm that this is unique to the latest release of ED2?  I'm having similar problems at Arizona with my PalEON branch from months ago (see #153). From what I pieced together with the helps of folks here, it appears to be as @ashiklom suggests where the hdf5 and ED compilers need to be the same (or at least not too different).  

I'm still working on all the details of what that exactly means, but given the amount of trouble folks seem to be having, we should probably make sure some note about the hdf5 setting and compiler makes it to the wiki for future reference.

**Comment by DanielNScott** [comment]
As I understand it, you will get this error if the module file was built by a newer version of gfortran than the one you're using to compile the model. At least I know I've gotten this error as a result of that problem before.

**Comment by DanielNScott** [comment]
Ok, just updated the wiki page for Ubuntu anyway. Sorry for causing a few headaches messing with the ED compilation stuff.

**Comment by DanielNScott** [comment]
Also, we should really fix our interface issue, it's really not good policy to rely on deprecated flags for the model to compile and hence force people to use old versions of a whole suite of software.

**Comment by ashiklom** [comment]
@DanielNScott :+1: to fixing the interface issue. @mpaiao discussed some possible ways to fix this on a [related issue thread](https://github.com/EDmodel/ED2/issues/86#issuecomment-109097099). I'd be willing to try to take a stab at this in the next few weeks since I was going to take a stab at tweaking the radiative transfer code anyway.

**Comment by DanielNScott** [comment]
Hey @serbinsh did you get this sorted out?

**Comment by serbinsh** [comment]
@DanielNScott Apologies.  Unfortunately I was on travel during much of this but am going to try give this a go again this week.....I will let you know.

**Comment by serbinsh** [comment]
@DanielNScott simply running install.sh -p bnl worked fine!  I need to dig into this a bit more to customize, for example not have a suffix of serbinsh but instead perhaps BNL but otherwise I think we are good.

**Comment by serbinsh** [comment]
@DanielNScott I see the suffix is the git tag....not a bit deal but I will likely just create a symlink for the general code used by our PEcAn web interface to remove this....

**Comment by DanielNScott** [comment]
Ok, you know you can use -g or --gitoff to keep it from tagging the build with git.

**Comment by serbinsh** [comment]
Haha, yeah I saw that after my comment…..apologies for the ongoing buffoonery


On May 9, 2016, at 2:26 PM, DanielNScott <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, you know you can use -g or --gitoff to keep it from tagging the build with git.

**Comment by DanielNScott** [comment]
Haha, @serbinsh no problem! Mostly I'm just relieved that in trying to make setting up ED easier I haven't actually screwed up other people's work. That and happy to have added a flag useful flag!
