### ISSUE TITLE
multiple site-level runs

### ISSUE THREAD

**Issue by ashehad** [EDmodel/ED2#160]
Hi All,

I was wondering if someone has done multiple site-level ED runs within a polygon. I'd like to move from a higher resolution to a lower resolution but at the same-time would like to capture as much heterogeneity as possible.

Best,
Ashehad

**Comment by mdietze** [comment]
Yes. you just need to define a *.site file for the polygon, in addition to the *.pss and *.css, and set the input mode appropriately so site is read. The site file will define fractional areas within a polygon that differ in soil texture, slope, aspect, elevation, and TCI.

**Comment by ashehad** [comment]
Thanks for your response, Mike. Is there any examples of *.site files? 
Best,
Ashehad

**Comment by mdietze** [comment]
https://github.com/EDmodel/ED2/wiki/Initial-conditions#Site_file_format_site

**Comment by ashehad** [comment]
Thanks
