### ISSUE TITLE
Fatal compilation error issue: Out of memory [University of Florida cluster]

### ISSUE THREAD

**Issue by MarconiS** [EDmodel/ED2#161]
Dear all,
Greetings, first of all. I am Sergio Marconi, first year PhD student at University of Florida (UFL), and I'd be honored to take part of the ED community. I am trying to install the latest version of ED on UFL cluster; I am using fort/icc as compilers. Apparently I am having a similar issue as @crollinson 's #153  . At first I was getting the error:
` ed_state_vars.F90: error #5102: Cannot open include file 'mpif.h' `
Now, pointing to the right MPI_PATH or disabling PAR_DEFS, compilation gets stuck for a long time
while compiling `ed_state_vars.F90` (i.e. about 10/15 minutes). After that, compilation reaches `average_utils.f90` source file, where returns me the error:
`Fatal compilation error: Out of memory asking for 61222912.
compilation aborted for average_utils.f90 (code 1)
make[1]: *** [average_utils.o] Error 1
make[1]: Leaving directory /home/smarconi/ED2/ED/build/bin-opt-E-master-7b564a2'
make: *** [all] Error 2` 
I am new with ED, so I can't figure it out if is just a naive error of my include.mk file (attached) or if it is a real issue. Can anyone give me a hint on where to look into to solve it? 
Thanks in advance,
Sergio

p.s. I've loaded the modules for intel compilers, openmpi, and hdf5

[include.mk.opt.ufl.txt](https://github.com/EDmodel/ED2/files/249253/include.mk.opt.ufl.txt)

**Comment by DanielNScott** [comment]
Sounds like you're running out of RAM on the machine you're installing the model on. I'd say you should try other applications, opening a system monitor to check you have plenty of RAM available, (I believe 1G should be plenty) and trying again.

**Comment by DanielNScott** [comment]
Actually I just saw you're on a cluster. If this is a batch job being executed via a job scheduler, you may need to make sure you are allocating enough memory.

**Comment by MarconiS** [comment]
Thank you @DanielNScott! Improving RAM to 1gb solved the issue. Sorry for the very naive question.

**Comment by DanielNScott** [comment]
No problem @MarconiS, I'm glad that was it!

**Comment by DanielNScott** [comment]
Also, just for future reference, 1G is way higher than it actually needs to be.
