### ISSUE TITLE
Info on canopy airspace variables?

### ISSUE THREAD

**Issue by DanielNScott** [EDmodel/ED2#164]
Is it written down somewhere in the model? ```ed_state_vars.f90``` just says, re ```csite%can_co2``` for example, that it's the mixing ratio of canopy air. Are the lower and upper bounds of the integration the ground and boundary layer respectively?

I figured I'd ask so it'd be a matter of record, rather than figuring it out myself and making someone else potentially duplicate that footwork later... Not to mention, I'm sure @mpaiao knows...!

**Comment by mpaiao** [comment]
The canopy air space is supposed to represent the air that fills the space between different cohorts.

The lower boundary is the ground.  The upper boundary is defined by can_depth, which is the average height of canopy trees, weighted by basal area.  We impose a minimum depth of 5m just to make sure the heat capacity isn't too low.

**Comment by DanielNScott** [comment]
Great, thanks for the info marcos!
