### ISSUE TITLE
compile error, Makefile:8: include.mk.opt: No such file or directory

### ISSUE THREAD

**Issue by fabeit** [EDmodel/ED2#166]
I am having troubles compiling ED, I have noticed the build folder has changed and also some of the compiling files. I get this error and I tried different things in the makefile, previous I had include.mk.$(OPT), but now this is not working, neither is working include.mk.opt. I did create a symbolic link with the ln command.

No platform specified, defaulting to gfortran.
No optimization level specified, defaulting to E.
Git found, it will be used to tag things.
To disable revision tagging, use --gitoff or -g.
Makefile:8: include.mk.opt: No such file or directory
make: Warning: File `dependency.mk' has modification time 0.96 s in the future
make: *** No rule to make target `include.mk.opt'.  Stop.

**Comment by DanielNScott** [comment]
Are you using gfortran? Have you tried ```install.sh --clean``` followed by ```install.sh```?

**Comment by fabeit** [comment]
It was just that I used an old include.mk.opt file that had the wrong path for include.mk
