### ISSUE TITLE
Can't generate the land/sea mask for a regional run using mpiexec

### ISSUE THREAD

**Issue by MarconiS** [EDmodel/ED2#174]
Dear all, 
I am very sorry for opening issues for naive problems most of the time. I am trying to execute a regional run of ED using mpi (used mpifort/mpicc to compile ED). However, when it comes to generate the land/sea mask I get a `forrtl: severe (174): SIGSEGV, segmentation fault occurred`. The path seems to be right (otherwise I would have expected something like `orrtl: severe (29): file not found, unit 29, file ./inputs/GE`). Both LandUse and FAO databases I am trying to use come from http://bridge.atmet.org/users/data.php. Is it a problem of my compilation, of the h5 data, or anything else?
Thank you, and again sorry for bothering.

p.s. I've attached the output of my run.
[errorLand_Sea.txt](https://github.com/EDmodel/ED2/files/294064/errorLand_Sea.txt)

**Comment by mdietze** [comment]
The version we use is available here: https://pecan.gitbooks.io/pecan-documentation/content/developers_guide/Installing-PEcAn-Data.html#site-information

Have never tried to build those from scratch or use the old RAMS defaults (which may be the same?)

**Comment by mpaiao** [comment]
Just to complete the info, RAMS defaults have the same content as they were the source, but in ED you will need the hdf5 files that @mdietze listed.  I built some of these files a long, long time ago, and I may be able to find them somewhere in case anyone needs it.

**Comment by MarconiS** [comment]
thank you @mdietze and @mpaiao! I should solve the issue with that.
