### ISSUE TITLE
ED2 test run issue in ed_opspec.f90?

### ISSUE THREAD

**Issue by gklarenberg** [EDmodel/ED2#177]
Hi, on July 9th I downloaded the ED2 code and had it compiled on our HPC (University of Florida). When I try to do a test run (with an existing ED2IN file), I get

`>>>>  opspec_misc  error! in your namelist!`
`    ---> Reason:      Invalid STORAGE_RESP_SCHEME, it must be 0 or 1. Yours is set to -999...`

`--------------------------------------------------------------`
`                     !!! FATAL ERROR !!!                      `
`--------------------------------------------------------------`
`    ---> File:        ed_opspec.f90`
`    ---> Subroutine:  ed_opspec_misc`
`    ---> Reason:      Fatal errors at namelist - Misc settings`
`--------------------------------------------------------------`
` ED execution halts (see previous error message)...`

The problem is that I searched ed_opspec.f90 for STORAGE_RESP_SCHEME  to figure out where I need to change input settings, but this term does not exist. In fact, I searched all the files and it doesn't exist? Any pointers on what is going wrong here would be appreciated.
I'm also in touch with the people from our HPC (since they helped with setting up the include.mk file, and compiling), but I'm not sure if they'll be able to help.
Thanks in advance for any help! Geraldine
FYI I also downloaded ED2 code last year (May 2015) and as far as I recall a test run worked. Our HPC has been upgrading and moving so I wanted to take the opportunity to use the newest/latest ED2 code and re-compile everything.

**Comment by gklarenberg** [comment]
Update - I re-downloaded the code again today and this time STORAGE_RESP_SCHEME is present in ed_opspec.f90. Not sure what I did wrong the first time around... Will recompile and check if it works now.

**Comment by DanielNScott** [comment]
Sounds to me like your code isn't up to date with the mainline, or is some sort of mix between the mainline and some other branch.

From line 1586 of ed_opspec.f90:
```fortran
   if (storage_resp_scheme < 0 .or. storage_resp_scheme > 1) then
      write (reason,fmt='(a,1x,i4,a)')                                                     &
         'Invalid STORAGE_RESP_SCHEME, it must be 0 or 1. Yours is set to'                 &
        ,storage_resp_scheme,'...'
      call opspec_fatal(reason,'opspec_misc')
      ifaterr = ifaterr +1
   end if
```

Anyway, the ED complaint means you don't have the setting in the ED2IN, or the setting is bad. (see line 1570 of /run/ED2IN.) If you're using an old ED2IN it may need to be modified.

**Comment by serbinsh** [comment]
@gklarenberg My guess is that your ED2IN file is now out of date with the latest ED2 version.  This happens if you have an ED2IN and then the code changes but you don't then sync your ED2IN with the changes in the latest version.  In that case your ED2IN is read improperly and doesn't "line up" with the code.  Try grabbing the latest ED2IN from the templates folder, modifying it so that it matches with the settings you had customized previously and re-running.
