### ISSUE TITLE
ED2 - HDF5 issue on HPC

### ISSUE THREAD

**Issue by gklarenberg** [EDmodel/ED2#178]
I am trying to do a test run (Amazon SOI) of ED2 on our university's HPC, which uses HDF5-1.8.17.
However, I get the error:
`./ed_2.1-opt: error while loading shared libraries: libhdf5.so.10: cannot open shared object file: No such file or directory`
In the include.mk file, I have
`HDF5_INCS=-I/apps/intel/2016.0.109/hdf5/1.8.17/include`
`HDF5_LIBS=-L/apps/intel/2016.0.109/hdf5/1.8.17/lib -L/apps/lib/szip/2.1/lib -lhdf5 -lm -lhdf5_fortran -lhdf5 -lhdf5_hl -lz -lsz`
The correct Intel and HDF5 modules are loaded before I try to run, and people from our HPC helped me set up these paths so I assume they are correct. Should I ask them to check again, or does anyone know if this is a different issue.
I do have to run 
`export LD_LIBRARY_PATH=/apps/lib/szip/2.1/lib`
also, otherwise I get a similar error about szip libraries.
Thanks!

**Comment by mpaiao** [comment]
I think the order matters in HDF5_LIBS.  If your libraries are at different directories, then you may want to try something like:

```Makefile
HDF5_LIBS=-lm -lz -L/apps/intel/2016.0.109/hdf5/1.8.17/lib -lhdf5 -lhdf5_fortran -lhdf5_hl -L/apps/lib/szip/2.1/lib -lsz
```
I don't normally list szip libraries and it compiles fine, so perhaps you don't even need -lsz.

**Comment by gklarenberg** [comment]
Thanks! So I took out the whole zip part all together and recompiled, and it seems like that did the trick - thanks!
I now have some error a parallel process being aborted :-/ but it seems like there are no issues with libraries anymore.
