### ISSUE TITLE
Soil heat flux

### ISSUE THREAD

**Issue by lucianainpa** [EDmodel/ED2#188]
Hi,
I’d like to know what variable can I use for soil heat flux, RSHORT  (down)  flux and RLONG (down). 
is this: MMEAN_SENSIBLE_GG_PY   , MMEAN_ATM_RSHORT_PY ,MMEAN_RLONG_GND_PY ?

**Comment by rgknox** [comment]
Hi @lucianainpa 

I think you are right on the first two.  The GG tag indicates sensible heat flux from "ground layer to ground layer", it should be a vector with the dimensions of the soil-column.  One of the fluxes may include sensible heat flux from the surface into the top soil layer, but its been a while so I forget.

For RLONG flux that is incident on the top of the canopy in the down direction, I would use MMEAN_ATM_RLONG_PY.  For RLONG flux up, use MMEAN_ATM_RLONGUP_PY.


There are also a few variables for both short and longwave radiation that will track how much is absorbed in soil, leaf, wood, etc.

I was able to surf through the different registered variables by keyword searching MMEAN_RLONG in ed_state_vars.F90, that is where you will find them defined.  You can also then see what types of files they will be sent to, see "eorq_keys"

**Comment by lucianainpa** [comment]
Thank you  Ryan.

**Comment by lucianainpa** [comment]
What does MMEAN_SAPA_STORAGE_RESP_PY mean?
What is the correct interpretation for MMEAN_SMOIST_GG_PY?
What is the name of MMEAN_WSHED_WG_PY, MMEAN_WOOD_WATER_PY and MMEAN_QTHROUGHFALL_PY?
This variable is in the canopy: MMEAN_CAN_VPDEF_PY?
What it means: MMEAN_AF_DECOMP_PY and this MMEAN_A_OPEN_PY
Why this variable always has zero value MMEAN_LEAF_DROP_PY? Do you also find zero value for it?
I'm trying to calculate the mortality rate for each PFT, is it possible?

**Comment by xiangtao-princeton** [comment]
Hi, @lucianainpa I'm checking the current open issues now. Given that this is a fairly old issue, are you still seeking answers for the questions?

**Comment by lucianainpa** [comment]
Hi @xiangtao-princeton 

I solved the problem.
Thank you.
Best regards
