### ISSUE TITLE
BDEAD value

### ISSUE THREAD

**Issue by lucianainpa** [EDmodel/ED2#192]
Please, Can someone say what it means: "bgb_frac" "and agb_frac", What value should be assigned?

For "agf_bs(pft) " is = 0.7? for all?
cpatch%bdead(ico) is the BDEAD for each cohort?

I'm trying to calculate the value of BDEAD. In my simulations the value of BDEAD decreased:
Bdead was 19.9 kg C m.-2, After 50 years it has decreased to 13 kg C.m-2. This effect reflects on above-ground biomass, so it also decreases. 
I'm trying to understand why BDEAd decreases.  Has anyone found this kind of result?

**Comment by mdietze** [comment]
https://github.com/EDmodel/ED2/wiki/PFT-parameters

**Comment by lucianainpa** [comment]
Thank you @mdietze

**Comment by xiangtao-princeton** [comment]
@lucianainpa It seems to be resolved. I'm closing it now
