### ISSUE TITLE
dlwrf

### ISSUE THREAD

**Issue by lucianainpa** [EDmodel/ED2#195]
Hi all, 

I would like to know if the variable dlwrf is incoming longwave radiation toward surface or is longwave radiation balance at the top of the atmosphere?
Regards.

**Comment by mdietze** [comment]
All met variables are at the interface between the Canopy Air Space and the lower boundary of the atmosphere

**Comment by lucianainpa** [comment]
Thank you @mdietze

**Comment by xiangtao-princeton** [comment]
@lucianainpa I'm closing this issue since it is resolved
