### ISSUE TITLE
Met driver header file and netcdf files

### ISSUE THREAD

**Issue by fabeuw** [EDmodel/ED2#20]
Hello,
I was wondering if anybody could explain how to create a header file. I have look at several templates but I am still confused.

Is it possible for ED to read directly the Sheffield met files in .nc format?

**Comment by mdietze** [comment]
The documentation about the met header file and the met file format is here: https://github.com/EDmodel/ED2/wiki/Drivers#meteorology-header-file

I haven't worked with the Sheffield met but you'd want to make sure the variable names and units are converted to what ED2 needs.

**Comment by fabeuw** [comment]
Thank you! 
And what is the meaning of these variables? 
{<nlon>, <nlat>, <dx>, <dy>, <xmin>, <ymin>

**Comment by mdietze** [comment]
Number of longitude grid cells
Number of latitude grid cells
Size of longitude grid cell (degrees)
Size of latitude grid cell (degrees)
Minimum longitude 
Minimum latitude 

If your doing a single site run you'll probably have the best luck setting the first 4 to 1 and then rounding down your location to the nearest whole degree

**Comment by fabeuw** [comment]
I think this info could be included either in the wiki page or in the met driver header file. Yes I am doing a single site run, the test run that I have works well by also leaving the lat and long with two decimal points. Probably a detail, but in what sense are lat/long minimum? Thanks.

**Comment by mdietze** [comment]
Good point, this was just an oversight.  Wiki had been updated
