### ISSUE TITLE
Cannot open met driver input file

### ISSUE THREAD

**Issue by fabeuw** [EDmodel/ED2#21]
---> File:        ed_met_driver.f90
    ---> Subroutine:  read_met_drivers_init
    ---> Reason:      Cannot open met driver input file /mnt/met_data/h5/WIND_2000FEB.h5!

Given that the h5 files exists and that I am able to open it with HDFview, what could cause this error message?

**Comment by mdietze** [comment]
This error message is generated by the following chunk of code:

         !----- Create the file name and check whether it exists. -------------------------!
         write(infile,fmt='(a,i4.4,a,a)')   trim(met_names(iformat)), year_use             &
                                           ,mname(current_time%month),'.h5'
         inquire(file=trim(infile),exist=exans)
         if (exans) then
            call shdf5_open_f(trim(infile),'R')
         else
            write (unit=*,fmt='(a)'       )  '------------------------------'
            write (unit=*,fmt='(a,1x,i12)')  ' - METCYC1  =',metcyc1
            write (unit=*,fmt='(a,1x,i12)')  ' - METCYCF  =',metcycf
            write (unit=*,fmt='(a,1x,i12)')  ' - IYEAR    =',iyear
            write (unit=*,fmt='(a,1x,i12)')  ' - YEAR_USE =',year_use
            write (unit=*,fmt='(a)'       )  '------------------------------'
            call fatal_error('Cannot open met driver input file '//trim(infile)//'!'       &
                            ,'read_met_drivers_init','ed_met_driver.f90')
         end if

The key here is the "inquire" which actually checks if the file exists, not that ED can open it. This means that ED isn't finding the file.  Can you check that the full file path is correct and there's no typos?  Could you also check if the same error occurs if you move the files somewhere else (eg your home directory) -- there's a small chance that the mnt has some sort of error

**Comment by fabeuw** [comment]
Michael you were right, it was an issue with a file name, thank you. I get another error code tough with all the following variables, the h5 files were created just like the other varialbes and have the same
# nbdsf:  near IR beam downward solar radiation [W/m2]
# nddsf:  near IR diffuse downward solar radiation [W/m2]
# vbdsf:  visible beam downward solar radiation [W/m2]
# vddsf:  visible diffuse downward solar radiation [W/m2]

DATASET: nddsf
 DOES NOT HAVE DIMENSIONS THAT MATCH THE
 SPECIFIED INPUT, OR LAT/LON GRID
           3
         248         361         181
         992         361         181
 In file:  /mnt/met_data/h5/DS314.SA.ODI.SW_2000JAN.h5
 Dataset:  nddsf
 doesn't have dimensions that match the
 specified input, or latitude/longitude grid...
 NP_DSET  =    248
 MET_NLON =    361
 MET_NLAT =    181
 NDIMS    =      3
IDIMS (    1) =   992
IDIMS (    2) =   361
IDIMS (    3) =   181
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
--------------------------------------------------------------
                     !!! FATAL ERROR !!!                      
--------------------------------------------------------------
    ---> File:        ed_met_driver.f90
    ---> Subroutine:  read_ol_file
    ---> Reason:      Mismatch between dataset and specified input

this is the section of the met header file relative to it 
/mnt/met_data/h5/DS314.SA.ODI.SW_
1 1 1. 1. 16.50 2.50
6
'lon'    'lat'     'nddsf'   'vddsf'    'nbdsf'    'vbdsf' 
10800.0  10800.0   10800.0    10800.0    10800.0    10800.0
2        2         1          1          1          1

and again all the other drivers are fine and in fact I can run the model with the SW_.

**Comment by mdietze** [comment]
The time step in the file does not correspond to what you specified in the met header file, thus the number of rows is different from what Ed expected

**Comment by fabeuw** [comment]
Thanks again that was the issue, I used some guesswork calculation to figure out the timestep :-)
