### ISSUE TITLE
easy way to specify changing CO2 input?

### ISSUE THREAD

**Issue by wimverbruggen** [EDmodel/ED2#215]
Dear ED2 community,

I'm trying to find a convenient way to feed the atmospheric CO2 level into ED2. I have about 10 years of meteo data which I want to use in a loop. I would like to spin up the model using the pre-industrial level of atmospheric CO2, then run the model for another 250 years while increasing the CO2 each year up to the current level.

Is there a way, in the current version of the master code, to do this without creating a meteo driver file for each month of my 250 year run explicitly, so that I can just keep using my current met driver files in a loop? For example by using an extra input file that contains CO2 vs. year?

Cheers,
Wim

**Comment by mdietze** [comment]
The ED_MET_HEADER lets you split different parts of the met data into different files if you want, so I don't see any reason you can't put CO2 in one file and everything else in another. Once you do that you can easily just create simlinks in place of real files for the 250yr of met that you want to cycle (i.e. met from 1750 can just be a simlink to the met from 1990) -- I don't THINK there's anything in the files themselves that would mess ED2 up (other than keeping track of leap years)

**Comment by wimverbruggen** [comment]
Thank you Mike, I implemented this and it seems to work perfectly!
