### ISSUE TITLE
Bug in structural growth module

### ISSUE THREAD

**Issue by manfredo89** [EDmodel/ED2#225]
I am experiencing a segmentation fault at structural_growth.f90:138
BT:
```
Image              PC                Routine            Line        Source             
ed_2.1-dbg         0000000003DD9FE2  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AB0264125E0  Unknown               Unknown  Unknown
ed_2.1-dbg         0000000002EE08CB  structural_growth         138  structural_growth.f90
ed_2.1-dbg         00000000030E56A4  vegetation_dynami          94  vegetation_dynamics.f90
ed_2.1-dbg         0000000000C7DEF5  ed_model_                 397  ed_model.F90
ed_2.1-dbg         0000000000414090  ed_driver_                296  ed_driver.F90
ed_2.1-dbg         000000000040EE41  MAIN__                    281  edmain.F90
ed_2.1-dbg         000000000040C5AE  Unknown               Unknown  Unknown
libc-2.17.so       00002AB026844C05  __libc_start_main     Unknown  Unknown
ed_2.1-dbg         000000000040C4A9  Unknown               Unknown  Unknown

```

It looks like the variable h_edge is neither initialized nor assigned a value.
I am not sure when this variable was introduced. Initially the file had a number (0.5) that was then transformed into a parameter h_edge.

This should affect all simulations, including the ones without PFT 17. 
Temporary fix is to add 

`h_edge = 0.5 
`

at line 116.

@mpaiao I remember that you asked me to transform that number into a parameter, do you remember if that was with the first or the second PR? Since you pulled the main branch, did you notice any crash?

I will soon update the code with new development and with a fix for that part.

**Comment by mpaiao** [comment]
@manfredo89 I think I saw this problem, but I fixed in my branch by initializing h_edge in ed_params.f90.
