### ISSUE TITLE
Events example

### ISSUE THREAD

**Issue by manfredo89** [EDmodel/ED2#232]
I'm trying to make a new event that would be similar to harvesting. I was wondering if anyone has used the event files and could provide an XML using the event_harvest subroutine.
@mdietze I've seen that you have been working with that, do you have such a file?

Thanks

**Comment by mdietze** [comment]
Here are some example events files, mostly for agricultural events
https://www.dropbox.com/s/mkejazyxxlf0qbi/events.tgz?dl=0

**Comment by manfredo89** [comment]
Thanks Mike,
I'll just post here a minimal example take from your event files so that in case the link breaks there is a reference for future users...


```
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "ed_event.dtd">
<eventlist>

<!---  Planting event  --->
<event>
  <year> 2001 </year>
  <doy>  275  </doy>
  <plant>
    <pft>     13       </pft>
    <density> 7.54  </density>
  </plant>
</event>
</eventlist>
```

**Comment by mdietze** [comment]
updated the wiki with this example as well
