### ISSUE TITLE
GitHub equivalent of Bzr v. 82?

### ISSUE THREAD

**Issue by mrjohnston** [EDmodel/ED2#233]
@mpaiao Do you know what the GitHub equivalent of ED version 82 on Bzr might be? Apparently that's the parent version of Ke's branch (which is the one I'm currently using). Thank you!

**Comment by mpaiao** [comment]
@mrjohnston If @ke-zhang  branched directly from the mainline, then I think it's this one 
https://github.com/EDmodel/ED2/releases/tag/rev-82

**Comment by mrjohnston** [comment]
@mpaiao Great, I appreciate it! I'll work under that assumption unless @ke-zhang says otherwise.

**Comment by ke-zhang** [comment]
@mrjohnston @mpaiao  Marcos is right.
