### ISSUE TITLE
fs_open is updated but not copied into rk4type

### ISSUE THREAD

**Issue by xiangtaoxu** [EDmodel/ED2#236]
In the current mainline master, copy_patch_init is called before canopy_photosynthesis in rk4_driver.f90
```fortran
                !---------------------------------------------------------------------------!
                !     Set up the integration patch.                                        !
                !---------------------------------------------------------------------------!
                call copy_patch_init(csite,ipa,initp,patch_vels)
                !---------------------------------------------------------------------------!
                
                
                !----- Get photosynthesis, stomatal conductance, and transpiration. --------!
                call canopy_photosynthesis(csite,cmet,nzg,ipa,cpoly%ntext_soil(:,isi)       &
                                          ,cpoly%leaf_aging_factor(:,isi)                   &
                                          ,cpoly%green_leaf_factor(:,isi))
                !---------------------------------------------------------------------------!
```

Since canopy_photosynthesis updates fs_open, this information is not copied into _**initp**_, and the integrator uses fs_open from the last time step. This can lead to problems in my hydrodynamic calculation. Although I can tune the new plant hydro codes to maintain compatibility, I wonder what is the reason to place copy_patch_init before canopy_photosynthesis? In older versions like rv84, copy_patch_init is after cnaopy_photosynthesis

**Comment by xiangtaoxu** [comment]
I think I know why copy_patch_init is before canopy_photosynthesis now. It's related with initialization of leaf boundary layer conductance.....

In general, leaf_gbw is initiated in ed_init_atm for cohorts that are resolvable. However, in cases where lots of small 'unresolvable' cohorts are fused after initialization, the fused cohort become resolved due to the increase of nplant. But their leaf_gbw remains 0, which will lead to 'dividing by 0' in photosynthesis calculation.

In copy_patch_init, leaf_gbw is updated from rk4type, which is against the purpose of the subroutine.... I think it would be better to update leaf_gbw after cohort fusion during initialization....

@mpaiao Does this sound reasonable to you?

**Comment by mpaiao** [comment]
@xiangtaoxu It is reasonable, although I think the best strategy would be to check all variables that are updated in canopy_turbulence/canopy_turbulence8, decide what should be the best initial value (zero or something else), then assign these numbers in init_ed_patch_vars and init_ed_cohort_vars.  By doing this we would still be able to use the fusion routines as they are and we would be able to eliminate the single-precision functions and routines in canopy_turbulence.f90 (something @manfredo89 brought up in issue #226).

**Comment by xiangtaoxu** [comment]
Yes, I agree. For now, I just added a quality check in canopy_photosynthesis, which calls leaf_aerodynamics to update leaf_gbw if leaf_gbw is 0. and the cohort is resolvable. This helps the test suites in debugging mode to pass. I will later communicate with @manfredo89 and find better ways to update leaf_gbw later.
