### ISSUE TITLE
Fuse / Terminate / Split order

### ISSUE THREAD

**Issue by manfredo89** [EDmodel/ED2#237]
I've seen that most Fuse / Terminate / Split calls happen in the same order. However in [reproduction.f90](https://github.com/EDmodel/ED2/blob/master/ED/src/dynamics/reproduction.f90#L473-L477) the order is different (terminate / fuse / split). Is there a reason for this? If I think about the logic of it, it should always be the same. Also if this is the case we could maybe create a unique procedure that calls the 3 subroutines.

**Comment by mpaiao** [comment]
@manfredo89 I don't see any reason why the order should be different in reproduction, actually in my branch I'm using fuse/terminate/split.  Fusion preserves biomass and necromass, while termination artificially kills trees, so at least in terms of carbon conservation, it's better to try to fuse small cohorts before terminating them.
