### ISSUE TITLE
Duplicate update to NGross_min  in utils/update_derived_props.f90

### ISSUE THREAD

**Issue by larsonej** [EDmodel/ED2#241]
Lines 833 and 835 both update Ngross_min. It seems like line 833 should be removed. Just wanted to check before making a pull request.

**Comment by mpaiao** [comment]
Could this be a typo in line [835](https://github.com/EDmodel/ED2/blob/41b61dcb9368ee06ae62c9ca15c86f380293f814/ED/src/utils/update_derived_props.f90#L833)? I'm not familiar with these variables, but it looks like the right-hand side of line 833 is gross budget and the rhs of line 835 is a net budget.

**Comment by larsonej** [comment]
I agree that line 835 calculates net flux and should refer to it. I'll make this change and create a pull request.
