### ISSUE TITLE
Boundry heat flux in bottom soil layer

### ISSUE THREAD

**Issue by larsonej** [EDmodel/ED2#243]
Hi All,
I've run across a problem in soil temperatures for Arctic simulations. The bottom soil layer seems to have a minimum temperature of 0 Celcius. I initialize the simulation with soil temps of about -20 C and within a year the whole column (0-2.5m) warms to zero or more. For reference, the mean air temperature at this site during this period is around 2 C. Is this a side effect of the hydrology boundary condition? There also does not seem to be a thermal conductivity term (or heat flux) in the heat equation from the lower boundary. I plan on adding one to maintain a permafrost boundary condition. Perhaps @mpaiao or @rgknox could comment on this. 
![boundary_heat_flux](https://user-images.githubusercontent.com/33552495/37851347-e99a65ee-2eb4-11e8-9a9e-e179e15d13ce.png)

**Comment by mdietze** [comment]
While allowing heat to flux downward indefinitely might create permafrost, it seems like a bit of a kluge. When we were working on getting persistent permafrost we found the following was helpful:

* The soil depth needs to be a LOT deeper to provide the required thermal mass (e.g. ~12m)

* The default soil albedo is too dark relative to remotely sensed observations for the arctic

* We needed to make a few changes to the snow physics (which we have in a branch somewhere) to generate compaction and thus a higher conductivity (e.g. wind compaction, frost hoar)

**Comment by mpaiao** [comment]
@larsonej The constant temperature is because the soil is partially frozen (it won't change temperature until water is completely frozen or completely melted).   In this case during the winter, heat flux between the bottommost layer and the layer should be always positive (as the layer is warmer), are you seeing this in the results? 

@mdietze's suggestion should make some difference and the first two points should be easy to test (changing NZG/SLZ and using a more reflective soil color, you can change both of them directly in ED2IN).  But it would be good to verify the heat fluxes to make sure there isn't any problem in the heat flux in the partially frozen soils.

**Comment by mdietze** [comment]
I wouldn't 'tune' the albedo to match the soil temperature, but Carl Davidson's thesis did find that the ED2 default snow albedo was not consistent with satellite observations (e.g. papers by Michael Loranty). I think you can defensibly move that parameter up to the empirical mean and then start sorting out the remaining issues

**Comment by larsonej** [comment]
Hi All,
Modifying the soil and snow albedo had small effects on the 2m and deeper
soil temperatures. However, the thermal conductivity used in the model was
an order of magnitude too high for peat and about a factor of 2 too high
for most mineral soils. Reducing the thermal conductivity and modeling a
deeper soil seems to give much more realistic values.
Erik

On Thu, Mar 29, 2018 at 3:30 PM, Michael Dietze <notifications@github.com>
wrote:

> I wouldn't 'tune' the albedo to match the soil temperature, but Carl
> Davidson's thesis did find that the ED2 default snow albedo was not
> consistent with satellite observations (e.g. papers by Michael Loranty). I
> think you can defensibly move that parameter up to the empirical mean and
> then start sorting out the remaining issues
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EDmodel_ED2_issues_243-23issuecomment-2D377346687&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=uJsb92W0cPZc-WrMGDoJaYBpyra3HRxkJwvTFq8XI_s&m=XQad2xDL6-2mvGNbwfMdhn3Z3TsCxoLCRFXHwjfgBHs&s=RaoqPRS2nF2QocYj2ynQ0sFDFpW3qF_n2xi9RyU1MMc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Af-5F4bziQGCxZW7t9olzB7HiCTZ-2D5Vigfks5tjTZggaJpZM4S5XJE&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=uJsb92W0cPZc-WrMGDoJaYBpyra3HRxkJwvTFq8XI_s&m=XQad2xDL6-2mvGNbwfMdhn3Z3TsCxoLCRFXHwjfgBHs&s=yjrQRWRtXjHxYHLC1KJkLEErq85GseL4fzulGP-kehM&e=>
> .
>



-- 
Erik Larson
Postdoctoral Fellow
Department of Organismic and Evolutionary Biology
Harvard University

**Comment by mpaiao** [comment]
@larsonej I think the thermal conductivity for peat came directly from LEAF-3, and as far as I remember no one has changed since then.  For the mineral soil conductivities, I used the numbers from Monteith and Unsworth (2008) book and applied a de Vries model to get the conductivities for different textures. Back then I couldn't find a better approach and I couldn't even find thermal conductivity for silt.

It looks like you have found information on the soil conductivity for different textures.  Should we update the defaults in ED2?

**Comment by larsonej** [comment]
Currently, ED calculates thermal conductivity in two ways; 1) look up table
based on specified soil type and 2) calculating thermal conductivity based
on specified sand and clay fractions. So far, I've changed the lookup table
values (ed_params) for soil type 12, peat. These values were way off
(factor of 10 in thermal conductivity). The default values in this table
for other soil types could probably be modified as well, although they are
at least closer to observed estimates (factor of ~2 or less depending on
soil moisture).

Method 2, calculating the thermal conductivity from composition will never
work for peat, since peat is mostly organic material (conductivity of
~0.08) and this method requires the fractions of clay, sand, and silt to
sum to 1. This could be fixed by adding a fourth constituent of organic
material and requiring the sum of all 4 fractions be 1. I think this would
be a useful future update and I'll put this on my to-do list.


On Tue, Apr 17, 2018 at 12:55 PM, Marcos Longo <notifications@github.com>
wrote:

> @larsonej
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_larsonej&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=uJsb92W0cPZc-WrMGDoJaYBpyra3HRxkJwvTFq8XI_s&m=gFVc7D3FWCWAVaU9-sg-65olvHch0GTzqnWSF8pzof0&s=zVUpfz1iWj7nVA2-8tq-l1dR0u4OZQLjc-Phr_YO1yk&e=>
> I think the thermal conductivity for peat came directly from LEAF-3, and as
> far as I remember no one has changed since then. For the mineral soil
> conductivities, I used the numbers from Monteith and Unsworth (2008) book
> and applied a de Vries model to get the conductivities for different
> textures. Back then I couldn't find a better approach and I couldn't even
> find thermal conductivity for silt.
>
> It looks like you have found information on the soil conductivity for
> different textures. Should we update the defaults in ED2?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EDmodel_ED2_issues_243-23issuecomment-2D382065818&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=uJsb92W0cPZc-WrMGDoJaYBpyra3HRxkJwvTFq8XI_s&m=gFVc7D3FWCWAVaU9-sg-65olvHch0GTzqnWSF8pzof0&s=ll-OPoTFO4pQ3A-zPyEwoARlhSaBDLv_TkGeqNDDAF8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Af-5F4b5Jd2jUHD9EDagAViCwBtTuiaw7cks5tph5lgaJpZM4S5XJE&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=uJsb92W0cPZc-WrMGDoJaYBpyra3HRxkJwvTFq8XI_s&m=gFVc7D3FWCWAVaU9-sg-65olvHch0GTzqnWSF8pzof0&s=_kIGkI1oumFUb5PE9JdiDyp8ezpQvt_Dc3_pP5Kq6rA&e=>
> .
>



-- 
Erik Larson
Postdoctoral Fellow
Department of Organismic and Evolutionary Biology
Harvard University
