### ISSUE TITLE
Seed Rain is not accumulated

### ISSUE THREAD

**Issue by xiangtaoxu** [EDmodel/ED2#249]
I notice that seed_rain is not accumulated into csite%repro. Instead, the seed_rain is added to rectest%nplant **temporarily** every month. 

https://github.com/EDmodel/ED2/blob/cf2e9609fb10c41f238ba988276bcebe9da5c414/ED/src/dynamics/reproduction.f90#L243-L246

This caused me some problems when seed_rain * one_plant_c is equal or smaller than min_recruit_size (in ed_params.f90). In some of my simulations in grasslands, one big drought killed all grass cohorts. In this case, csite%repro for grass would always be 0 (no reproduction). I was expecting the seed_rain can repopulate the patch but it never did because seed_rain is always smaller than min_recuit_size. Accumulating seed_rain can solve this problem and makes more ecological sense. In addition, seed_rain was accumulated in older versions of ED2.

I can create a PR if there's no specific reasons to not accumulate seed_rain.

**Comment by fabeit** [comment]
Since which version seed_rain does not accumulate? I am curious about this case. I always thought that seed rain was too low because it didn't allow a dead pft to come back. So I am wondering if it's because of seed rain not accumulating or because seed rain is not too low. I don't know if it's completely true that it should accumulate because seeds in the seed bank don't remain viable forever.

**Comment by xiangtaoxu** [comment]
@fabeit I'm not sure when this has changed. I knew the older version like rv76 (more than 5 years ago!) does accumulate seed_rain.

If min_recruit_size == 0, there will be no problem, because any tiny seed_rain of a dead pft can repopulate patches, However, this can lead to lots of small cohort and frequent cost to call fuse_cohorts to my understanding. My current strategy is (1) to let seed_rain accumulate and (2) set seed_rain as 1/12 of min_recuit_size. So under extreme case where one PFT is dead, a new cohort can come back after one year.

**Comment by fabeit** [comment]
@xiangtaoxu thanks for the clarification, that seems a good way of doing it. But do you move the accumulated seed rain to carbon litter after a certain time?

given   `min_recruit_size(ipft) = min_plant_dens * one_plant_c(ipft)` 
in which cases is min_recruit_size = 0? I guess only if you initialdensity is = 0. I never understood why you need an initial density in bare ground runs.

**Comment by xiangtaoxu** [comment]
@fabeit I meant forcing min_recruit_size to be zero instead of calculating min_plant_dens * one_plant_c.

The accumulated seed_rain will go into csite%repro structure. csite%repro will be zeroed every time when there's enough seeds for the model to start new cohorts.

Haha, I agree the init_density is not so intuitive. My understanding is that init_density means initial seed bank of the site, which can be different from seed_rain.
