### ISSUE TITLE
Water Budget Issues

### ISSUE THREAD

**Issue by crollinson** [EDmodel/ED2#251]
I'm trying to do a run at Willow Creek (45.805822 N, -90.079722 E) and keep running into water budget/hydrology issues with both Ameriflux and NLDAS met products.  The timing of the error changes a bit if I tweak some settings, so I don't think it's a met issue.   It's usually 2-5 years into the simulation, so I don't think it's an initialization issue.

The most common error I get is a Water Budget fail:
```
|--------------------------------------------------|
|          !!! ): Water budget failed :( !!!       |
|--------------------------------------------------|
 TIME           : 2001 05 20  9000.
 LAI            :   5.6022549E+00
 VEG_HEIGHT     :   1.9650862E+01
 CAN_DEPTH      :   1.9650862E+01
 RESIDUAL       :  -1.2599268E+01
 INITIAL_STORAGE:   3.6714938E+02
 FINAL_STORAGE  :   3.6714938E+02
 DELTA_STORAGE  :  -1.2598572E+01
 PRECIPGAIN     :   0.0000000E+00
 DENSITY_EFFECT :  -1.2106972E-05
 LOSS2ATM       :  -7.0817582E-04
 LOSS2DRAINAGE  :   0.0000000E+00
 LOSS2RUNOFF    :   0.0000000E+00
|--------------------------------------------------|

```
but I also have received this:
```
--------------------------------------------------------------
                     !!! FATAL ERROR !!!                      
--------------------------------------------------------------
    ---> File:        lsm_hyd.f90
    ---> Subroutine:  updateWatertableSubtract
    ---> Reason:      Bad dw!
--------------------------------------------------------------
 ED execution halts (see previous error message)...
--------------------------------------------------------------
```

I'm trying the hybrid integrator with SMP compilation (what I've been using for a long time now for PalEON).  clay = 0.09, sand = 0.63, deepest soil layer is -1.17, and I've now tried a couple settings for ISOILBC.

I'll try to dig into this later today and find whoever last modified this code, but if anybody has any ideas, I'd really appreciate it!

If it helps, the template for what I started with can be found here: [ED2IN](https://github.com/crollinson/MetDownscaling_Manuscript/blob/master/ED_runs/4_runs/ED2IN_Base_MetManuscript) 

Only the file paths for input/output, met etc. change.

**Comment by xiangtaoxu** [comment]
Not sure whether this is relevant. 

I have modified the computation of water budget to include leaf/wood internal water (which should be zero if running without plant hydraulics). See line [597-611](https://github.com/EDmodel/ED2/blob/5c785c6005ff7c1655c8dcb07822d9ebeda5bfe5/ED/src/utils/budget_utils.f90#L597-L609) in utils/budget_utils.f90. It worked well for me for runs with and without hydraulics.

From the first error message, it seems the total water has decreased by a lot while there are no significant in-flux and out-flux of water. It might be helpful to print out the different water pools when the error is detected?

**Comment by crollinson** [comment]
Quick note: turning on plant hydro schemes apparently does NOT work with the hybrid integrator.  I can't get the simulation to start if I turn it to 1 or 2.

(I'll try more when I get back from the field)

**Comment by crollinson** [comment]
nano E

**Comment by xiangtaoxu** [comment]
Yes, currently the hydraulics does not work with hybrid...

**Comment by crollinson** [comment]
Turns out this issue is NOT resolved.  IED_INIT_MODE=2 is not initializing cohorts and looks like it might not be growing trees at all.
