### ISSUE TITLE
What version of Ubuntu do you use?

### ISSUE THREAD

**Issue by yanhuachuchu** [EDmodel/ED2#264]
What version of Ubuntu do you use?

**Comment by yanhuachuchu** [comment]
When I compiled, there were many cases where library files could not be found. I guess the version is incompatible. What version do you use?

**Comment by yanhuachuchu** [comment]
My question is the same as that of #201, but I don't know where to change the HDF5 path.

  Many thanks

**Comment by manfredo89** [comment]
Please post the compilation errors

**Comment by yanhuachuchu** [comment]
=== Finished dependencies ===
make[1]: Leaving directory '/home/yanhua/ED2/ED/build/bin-opt-E-master-24e6df6'
make ../../build//ed_2.1-opt-master-24e6df6
make[1]: Entering directory '/home/yanhua/ED2/ED/build/bin-opt-E-master-24e6df6'
/bin/rm -f hdf5_coms.F90
/bin/cp -f ../../src/memory/hdf5_coms.F90 hdf5_coms.F90
mpif90 -c -DUSE_INTERF=1 -DUSENC=0 -DPC_GFORTRAN -DUSE_HDF5=1 -DUSE_COLLECTIVE_MPIO=0 -DUSE_MPIWTIME=1 -g -ffree-line-length-none -fno-whole-file -O2 -fopenmp   -I../../src/include -I/usr/local/hdf5/include   -DRAMS_MPI -I/usr/local/hdf5/include hdf5_coms.F90
hdf5_coms.F90:3:7:

    use hdf5
       1
Fatal Error: Can't open module file ‘hdf5.mod’ for reading at (1): 没有那个文件或目录
compilation terminated.
rules.mk:317: recipe for target 'hdf5_coms.o' failed
make[1]: *** [hdf5_coms.o] Error 1
make[1]: Leaving directory '/home/yanhua/ED2/ED/build/bin-opt-E-master-24e6df6'
Makefile:51: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yanhuachuchu** [comment]
I use ubuntu16.04 LTS and install ED according to “Installation of Pre-Reqs on Ubuntu Using Gfortran” in Quick Start.

**Comment by manfredo89** [comment]
You need to add the path of your libraries. Note that in the include used during the make, you have the libraries link (https://github.com/EDmodel/ED2/commit/17aa2a533cb9bb230a353076c3a644d3135f68ed#diff-1180d98a8a5bacf7bbef412520ff40c2R51)
For example in my include I have something like
`HDF5_LIBS=-lz -L/usr/local/hdf5_mio/lib -lhdf5 -lhdf5_fortran -lhdf5_hl`
That mean that my libraries hdf5 hdf5_fortran and hdf5_hl are located in `/usr/local/hdf5_mio/lib `
Find the location of your libraries and edit the include file accordingly. Also make sure you have been using exactly the same compiler to produce those libraries as the one you use to compile ED.

**Comment by yanhuachuchu** [comment]
My problem is that I can't find the installation path for HDF5 because I use the "apt-get install" command. Would you like to download the installation package of HDF5 and install it again, or use the "apt-get install" command to install HDF5 directly?

**Comment by manfredo89** [comment]
Well it does not really matter. You just need to find the path where the library was installed. I read that by running  `dpkg -L <package_name(hdf5)>` you should be able to see the location of that package. I use Mac so I cannot confirm but it should not be difficult to find your path.

**Comment by yanhuachuchu** [comment]
Okay, I'll try it again. Thank you for your help. 
Thank you very much.

**Comment by xiangtaoxu** [comment]
@yanhuachuchu I think you can also use `which h5dump` to see the location of hdf5 library
