### ISSUE TITLE
Soil temperature off-track

### ISSUE THREAD

**Issue by femeunier** [EDmodel/ED2#266]
Does anybody know how to deal with soil temperatures off-track crash with ED2? The issue occurs always around the same approximate date (around midday, mid-April, middle of the rainy season for my site) when I move from one year of drivers to another. Where should I look at first? Drivers? Initial conditions? See attached files for details of the error.

[logfile.txt](https://github.com/EDmodel/ED2/files/2797986/logfile.txt)

**Comment by mpaiao** [comment]
@femeunier It looks like it's the deepest soil layer (which is a bit shallow for French Guiana, isn't it?).  The soil moisture does not look crazy, so I am wondering if it may be some inconsistency between water extraction and energy extraction for transpiration, as most of your roots access water from this layer.

I suggest running some tests with different settings to try to isolate the problem.  I would start with modules that control transpiration and water extraction.  Does it crash when you turn off plant hydraulics or if you use Leuning's stomatal conductance?

**Comment by femeunier** [comment]
Solved by using a correct parameterization of soil properties.
