### ISSUE TITLE
Trouble with met files using HDF5/1.8.13 library

### ISSUE THREAD

**Issue by Viskari** [EDmodel/ED2#27]
We are currently setting up the current version of ED2 to run our server, which has the newest version of HDF5 libraries, version 1.8.13, installed. However, when we try to run ED2 in it, we are running in to an issue with the met files, where it reads the temperature in as NaN. All the input files have been copied over from geo cluster on BU, where they run fine and without this problem, and as far as we can tell, the only difference is the HDF5 version.

Has there been anyone else with similar problems? And if so, are there any suggestions on how to approach this problem?

-- Toni

**Comment by fabeuw** [comment]
Have you opened the data with HDFView and inspected the data for any Nan? I am guessing that even one Na might cause the issue.
