### ISSUE TITLE
Possible code typo for lianas PFT?

### ISSUE THREAD

**Issue by LMurphy186232** [EDmodel/ED2#272]
https://github.com/EDmodel/ED2/blob/5c785c6005ff7c1655c8dcb07822d9ebeda5bfe5/ED/src/init/ed_params.f90#L676

In the code for other reasons and I saw this - perhaps this should be assigning lreflect_nir? Tagging @manfredo89, I think this was your code

**Comment by femeunier** [comment]
Definitely a typo that will be fixed as soon as we push the most recent changes to the liana pft. Good catch, thanks!

**Comment by LMurphy186232** [comment]
All right, I'll go ahead and close this then

**Comment by manfredo89** [comment]
Good catch indeed, I made a direct commit to fix the typo.
