### ISSUE TITLE
Can we compile ED using Intel Visual Fortran and Visual Studio on Windows OS? Or we have to compile ED on other OS (e.g., Linux)?

### ISSUE THREAD

**Issue by koxingazhu** [EDmodel/ED2#273]
Can we compile ED source codes using Intel Visual Fortran and Visual Studio on Windows OS? Or we have to compile ED on other OS (e.g., Linux)? Thank you.

**Comment by mpaiao** [comment]
I never tried to compile ED2 in Windows, I use only Linux and Mac.  But I can anticipate a few requirements for compiling in any new environment:

First, you will need to have HDF5 libraries that are compatible to the fortran and C compilers you are going to use. 

Also, it is possible/likely that the compilation will crash in ED/src/rsys.F90.  In case this happens, you may need to do the following:

1. Create a windows-specific compilation settings file in ED/build/make (e.g. include.mk.windows)
2. Set a unique name for CMACH (e.g. CMACH=WINDOWS)
3. Create the appropriate #if/ #elif blocks in ED/src/rsys.F90.  The actual changes (if any is needed) will depend on what Visual Fortran / Visual Studio requires for system-specific functions.

It is possible that you may even need to create new Makefiles, include.mk, etc. to deal with the Windows syntax.  I haven't used Windows for a very long time, but maybe ED2 users are more familiar with Windows and can help. 

Another (possibly easier) alternative is to install VirtualBox and download a virtual machine available at [PEcAn](https://pecanproject.github.io).  The virtual machine is a Linux environment.

**Comment by LMurphy186232** [comment]
I am a Windows user and I spent some time awhile ago trying to compile with Cygwin. It was a nightmare and I failed after wasting a LOT of time. I'm not saying it's not possible, especially if you feel very comfortable in setting up projects for Windows. But at least for me, it was far easier to use VirtualBox to get up and running (super easy, works right away), and when my needs went beyond that, installing Linux on an extra machine I have.

**Comment by serbinsh** [comment]
I would suggest using a version within a Docker container instead of trying to compile natively on Windows.  It will be MUCH simpler.


[iphone]
________________________________

**Comment by serbinsh** [comment]
For example, here is a Dockerfile used to run ED2 docker within PEcAn: https://github.com/PecanProject/pecan/blob/develop/models/ed/Dockerfile

You could modify this to fit your needs, etc to run ED2 via a docker run command instead of the natively compiled binary, but you can make this functionally very similar.

Shawn

**Comment by koxingazhu** [comment]
> I never tried to compile ED2 in Windows, I use only Linux and Mac. But I can anticipate a few requirements for compiling in any new environment:
> 
> First, you will need to have HDF5 libraries that are compatible to the fortran and C compilers you are going to use.
> 
> Also, it is possible/likely that the compilation will crash in ED/src/rsys.F90. In case this happens, you may need to do the following:
> 
> 1. Create a windows-specific compilation settings file in ED/build/make (e.g. include.mk.windows)
> 2. Set a unique name for CMACH (e.g. CMACH=WINDOWS)
> 3. Create the appropriate #if/ #elif blocks in ED/src/rsys.F90.  The actual changes (if any is needed) will depend on what Visual Fortran / Visual Studio requires for system-specific functions.
> 
> It is possible that you may even need to create new Makefiles, include.mk, etc. to deal with the Windows syntax. I haven't used Windows for a very long time, but maybe ED2 users are more familiar with Windows and can help.
> 
> Another (possibly easier) alternative is to install VirtualBox and download a virtual machine available at [PEcAn](https://pecanproject.github.io). The virtual machine is a Linux environment.

**Comment by koxingazhu** [comment]
> I never tried to compile ED2 in Windows, I use only Linux and Mac. But I can anticipate a few requirements for compiling in any new environment:
> 
> First, you will need to have HDF5 libraries that are compatible to the fortran and C compilers you are going to use.
> 
> Also, it is possible/likely that the compilation will crash in ED/src/rsys.F90. In case this happens, you may need to do the following:
> 
> 1. Create a windows-specific compilation settings file in ED/build/make (e.g. include.mk.windows)
> 2. Set a unique name for CMACH (e.g. CMACH=WINDOWS)
> 3. Create the appropriate #if/ #elif blocks in ED/src/rsys.F90.  The actual changes (if any is needed) will depend on what Visual Fortran / Visual Studio requires for system-specific functions.
> 
> It is possible that you may even need to create new Makefiles, include.mk, etc. to deal with the Windows syntax. I haven't used Windows for a very long time, but maybe ED2 users are more familiar with Windows and can help.
> 
> Another (possibly easier) alternative is to install VirtualBox and download a virtual machine available at [PEcAn](https://pecanproject.github.io). The virtual machine is a Linux environment.

Thank you for your help. I will try to install VirtualBox and download a virtual machine available at [PEcAn].
