### ISSUE TITLE
Disturbances/Logging & Patch Area

### ISSUE THREAD

**Issue by crollinson** [EDmodel/ED2#277]
Im in the process of tracking down some odd behavior with applying disturbances (or at least logging) over patches.   This is from my new [branch updating logging](https://github.com/crollinson/ED2/tree/Forestry_Testing), so it could be from my changes, but I don't think so.

Attached is a plot of DBH distributions across [7 harvesting scenarios from a quick test](https://github.com/MortonArb-ForestEcology/MANDIFORE_modeling/tree/master/WCr_Test_UnderstoryThin) at Willow Creek starting in 2006, harvesting in 2007-2011, and then recovery 2012-2020.   In all cases the fraction area harvest = 1 and the minimum patch age for harvest = 10.
- None2 = fraction area harvest = 0
- None = harvest above/below threshold = 0
- Above = harvest 100% stems _above_ 30 cm DBH for all PFTs
- Above_MaplesOnly = harvest 100% stems _above_ 30 cm DBH for _only PFT 11_
- Below = harvest 100% stems _below_ 30 cm DBH for all PFTs
- Above_MaplesOnly = harvest 100% stems _below_ 30 cm DBH for _only PFT 11_
- All = harvest 100% stems above _and_ below 30 cm DBH

[HarvestDifferences_Density.pdf](https://github.com/EDmodel/ED2/files/3611779/HarvestDifferences_Density.pdf)

Given how I've parameterized everything, the "all" scenario should get rid of everything in 2007, but that doesn't happen and instead it takes ~3 years to actually harvest everything.  The run starts with 4 x 70 year old patches.

I'm hoping it will be fairly straightforward to figure out what's going on and modify it, but wanted to throw it here in case anybody knows what's going on.  

Once I track down what's going on that's preventing me from harvesting 100% of the area, I'll be submitting a pull request with the new selective logging behaviors.  @mpaiao @mdietze -- let me know if either of y'all have thoughts.  I'm hoping to have everything sorted out and a PR in next week.

**Comment by mdietze** [comment]
I haven't looked at that code in a long time, but it was originally developed around the Hurtt product, which has a decadal time step. Maybe there's some implicit assumption in there that's dividing your rates by 10 and not detecting correctly that you're providing different rates every year?

**Comment by crollinson** [comment]
I think I see what's happening:  Under my current implementation, I forgot to make the potential area harvested equal to the fraction read from the driver.  This causes the patch to get the disturbed flag, but not biomass_harvest in lines 412-419 of disturbance.f90.  When this happens, the disturbance rate gets scaled in line 446: pot_area_loss(ipa,new_lu) = csite%area(ipa) * (1.0 - exp(-dist_rate)).

My first stab at a quick hack didn't work, but it should be pretty straight forward.

**Comment by crollinson** [comment]
Fixed it! 
[HarvestDifferences_Density.pdf](https://github.com/EDmodel/ED2/files/3617705/HarvestDifferences_Density.pdf)

Pull request will be coming in the next week or so.  Existing ED2 forestry schemes will remain in place; there will just be 2 lines added to the driver header to accommodate harvest rates below the DBH threshold as well as a new `ianth` option.
