### ISSUE TITLE
Met forcing has issues...

### ISSUE THREAD

**Issue by fabeuw** [EDmodel/ED2#28]
I am getting this error message after ED runs for roughly 40 days, simulation starts 1/1/1600. The HDF5 file seems to be fine. Any idea what might be trigger this?

Air specific humidity doesn't make sense... 
  - Polygon        :      1
 - Site           :      1
 - Date           : 02/09/1600
 - Time           : 09:00:00 UTC
 - Longitude      :  1.65000E+01
 - Latitude       :  2.50000E+00
 - Site spec. hum.:  3.26690E-02
 - Polygon sp. h. :  3.26690E-02
 - Minimum OK     :  1.00000E-06
 - Maximum OK     :  3.20000E-02
---------------------------------------------------
 
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
--------------------------------------------------------------
                     !!! FATAL ERROR !!!                      
--------------------------------------------------------------
    ---> File:        lapse.f90
    ---> Subroutine:  met_sanity_check
    ---> Reason:      Meteorological forcing has issues (check message).

**Comment by mpaiao** [comment]
I think the problem may be in the met forcing, just to confirm does the hdf5 file show values of this magnitude for the place you are running? Specific humidity of 32g/kg is a very high number, even for the tropics.  

Which meteorological forcing are you using (tower, reanalysis, other?).  In case it is reanalysis, it is better to use the 1st atmospheric level instead of surface values.  In case you are using tower data, double check the units (it must be kg_H2O/kg_moist_air).

**Comment by fabeuw** [comment]
I am using the Sheffield data converted to hdf5 using Ke's scripts. I have in fact in the hdf5 file four values above 32g/kg and several in the 30g/kg range. This is in Congo.

**Comment by mpaiao** [comment]
We never used Sheffield's specific humidity for the Amazon, we used NCEP reanalyses instead.  I couldn't remember why but you may have found the reason.  I know it's in the tropics, but 32g/kg with surface pressure of around 950hPa means that relative humidity is above 100% unless T>32°C. In the Amazon humidity is typically of the order of 18 g/kg.

I have never seen Sheffield's raw data, could it be that specific humidity is in mol_H2O/mol_air? If so, Sheffield data may be missing a factor of 0.018/0.029.

**Comment by fabeuw** [comment]
Thanks Marcos, I checked but the unit is kg I believe in the Sheffield data.The .nc file metadata is units = "kg kg-1", so I imagine that means g/kg as you said. Also pressure and temperature are in the range you mentioned so relative humidity is way above 100%. We will have to use something else instead of Sheffield. Is NCEP the only option we have for tropical Africa?
