### ISSUE TITLE
Soil evaporation calculation

### ISSUE THREAD

**Issue by xiangtaoxu** [EDmodel/ED2#285]
I noticed that current mainline uses saturated specific humidity (ground_ssh) instead of true specific humidity (ground_shv = ground_ssh * soil_moisture factor) when calculating soil evaporation
https://github.com/EDmodel/ED2/blob/7a39cd9de80d5551acd0753ee94470ca6facb933/ED/src/dynamics/rk4_derivs.F90#L1255-L1257

This can lead to unrealistically high soil evaporation during tropical dry seasons, creating extra plant water stress. I also checked earlier versions (rv84), which uses ground_shv instead of ground_ssh.

Just want to confirm this should be ground_shv. @mpaiao

**Comment by mpaiao** [comment]
As far as I remember, this should indeed be ground_shv, not ground_ssh.  Not sure why this has changed...  Thanks for checking this.

**Comment by xiangtaoxu** [comment]
I have just created a quick PR for this. I also urge people who run the master version in hot and dry ecosystems to check their evaporation and soil moisture values during dry months.
