### ISSUE TITLE
The ED-2.2 Merge

### ISSUE THREAD

**Issue by mpaiao** [EDmodel/ED2#288]
Opening this issue to discuss the ED-2.2 merge to the mainline, following the ED2 meeting in Nov 2019.

**Comment by mrjohnston** [comment]
**Compilation:** successful (platform: Cannon; compiler option ("kind"): E)

**Running:** terminates before any output is written with the following error:
 [+] Ed_Init_Atm...
OLD NPLANT:   1.0001395E+00
NEW NPLANT:   5.3516275E-01
OLD SIZE:     2.8055266E-01
NEW SIZE:     1.5028669E-01
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

--------------------------------------------------------------
                     !!! FATAL ERROR !!!
--------------------------------------------------------------
    ---> File:        fuse_fiss_utils.f90
    ---> Subroutine:  split_cohorts
    ---> Reason:      Cohort splitting didn't conserve plants!!!
--------------------------------------------------------------

**Comment by ashiklom** [comment]
@mrjohnston Would you be able to share your inputs and configuration for these runs with me? If so, I can add them to the new Continuous Integration test suite.

**Comment by mrjohnston** [comment]
@ashiklom That would be lovely, thank you! One quick caveat is that I wouldn't necessarily expect results to be great, since the phenology is specified incorrectly, the initial condition is simplified, etc. 
That said, this configuration with these inputs completes successfully using ED2.1 (but not using ED2.2 as of November -- as you can see above).

[Tonzi_InputsConfig.zip](https://github.com/EDmodel/ED2/files/4032015/Tonzi_InputsConfig.zip)

**Comment by mrjohnston** [comment]
@ashiklom That would be lovely, thank you! One quick caveat is that I wouldn't necessarily expect results to be great, since the phenology is specified incorrectly, the initial condition is simplified, parameters are not fully tuned, etc. 

That said, this configuration with these inputs completes successfully using ED2.1 (but not using ED2.2 as of November -- as you can see above).

[SemiArid_InputsConfig.zip](https://github.com/EDmodel/ED2/files/4032050/SemiArid_InputsConfig.zip)

**Comment by mpaiao** [comment]
@mrjohnston thanks for sending the crash case.  I may try to incorporate to my local tests too.

@ashiklom thanks for creating the continuous integration test suite.  I am running the old-school test suite for the current PR (which has helped me to identify a few other bugs in the code).  I also implemented a few other tests that I would like to integrate to the future test suite platform.  But just to clarify, what you are currently implementing is to identify whether the pull request runs or not, you are not trying to compare output with the current mainline, correct?

**Comment by ashiklom** [comment]
@mrjohnston Awesome, thanks! I'll try to incorporate those as soon as I can.

@mpaiao Yes, currently, I'm only testing if the model runs (currently, just the one run at UMBS; I'll try to add more as we go) complete without errors. In the future, I definitely think we should add more tests to check that outputs are reasonable, and perhaps even compare to previous runs. For the latter, I could even imagine that results from the latest runs could be stored automatically by the CI (perhaps after PRs are merged).

**Comment by mpaiao** [comment]
Thanks! I was asking because the test suite that @rgknox implemented in ED-2 a while back also compares the results, so we should keep it as part of the code for now.

**Comment by ashiklom** [comment]
Cool! Yeah, I don't plan on removing anything in the EDTS directory, at least for now. I think a good idea would be to incrementally port pieces of the previous Matlab-based test suite to R (or something else open source) and add it to the continuous integration.

**Comment by ashiklom** [comment]
@mdietze @mpaiao (and other admins) I propose that we create a GitHub tag (`v2.2.0`) corresponding to the current state of the `master` branch and then close this issue. The tag will make it easier to refer to this exact version for papers (and software that uses ED2, like PEcAn).

To create a tag:

Open the ED2 repository on your local machine and make sure it's up to date.

```
cd ED2
git checkout master
git pull upstream master
# or `git pull origin master` if you're working directly with this fork
```

Create the tag...

```
git tag v2.2.0
```

...and push it to GitHub.

```
git push upstream v2.2.0
```

**Comment by mdietze** [comment]
@ashiklom,  @mpaiao already tagged it https://github.com/EDmodel/ED2/releases

**Comment by mpaiao** [comment]
It's not tagged as v.2.2.0 though. Let me see if I can change it.

**Comment by mpaiao** [comment]
I renamed the released directly on GitHub (v.2.2.0).  @ashiklom, could you please check that it is working as it should? Thanks!

**Comment by ashiklom** [comment]
Looks great, thanks! Should this issue be closed? At this point, any new problems people run into should be their own issues.
