### ISSUE TITLE
Units in carbon budget, kg/m2/yr vs kgC/m2/yr

### ISSUE THREAD

**Issue by larsonej** [EDmodel/ED2#296]
Hi All,
There are many places in ed_state_vars (usually HR and NEP) where the carbon flux unit is labeled kg/m2/yr. I just want to double check that these should actually be kgC/m2/yr, consistent with GPP and NPP? At some point, we should fix the units in ed_state_vars. 
Erik

**Comment by mpaiao** [comment]
@larsonej Yes, they are all kgC/m2/yr.
