### ISSUE TITLE
Plant Functional Type wiki page doesn't render

### ISSUE THREAD

**Issue by dlebauer** [EDmodel/ED2#316]
Not sure what was here: https://github.com/EDmodel/ED2/wiki/Plant-functional-types, but it doesn't currently Render. Perhaps it should be replaced w/ descriptions from ED2IN?

**Comment by mpaiao** [comment]
I don't know why it was not working, but in any case, I rewrote the page and added a very simple table.  It should be visible now.

**Comment by dlebauer** [comment]
Thanks!

**Comment by pmoorcroft** [comment]
Thanks Marcos — much appreciated!

Best wishes for the New Year,

Paul.


On Jan 5, 2021, at 5:43 PM, Marcos Longo <notifications@github.com<mailto:notifications@github.com>> wrote:



I don't know why it was not working, but in any case, I rewrote the page and added a very simple table. It should be visible now.
