### ISSUE TITLE
Creating met data for extreme climate scenarios

### ISSUE THREAD

**Issue by koxingazhu** [EDmodel/ED2#325]
Dear all,
I want to simulate the response of forest carbon cycle to extreme climate events (e.g., ice storm, frost, drought). So, I need to create met data for those scenarios. For frost, I modified existing met data (only tmp and sh that highly related to frost) from NCAR reanalysis, however, the simulation results almost unchanged compared with baseline scenario. Why? Should I need also modify other met variables (some radiation vars)?

**Comment by larsonej** [comment]
As far as I know, ED has not been used extensively to simulate frost disturbance. Were you expecting defoliation or mortality? For mortality, look at the plant_min_temp and frost_mort in ed_params.f90. They are quite low for most trees, thus mortality is unlikely. I don't think ED2 includes frost defoliation. 

You will likely see larger effects with droughts, which ED has been used to simulate in multiple papers.

**Comment by mpaiao** [comment]
Just to follow up on Erik's correct comment, the frost mortality model is rather simple: if I remember correctly, it's briefly described in [Albani et al. (2006)](https://dx.doi.org/10.1111/j.1365-2486.2006.01254.x), which is back in ED1 days. 

I think their original idea was to prevent southern pines to live too far north, but if you are simulating hardwoods in the CONUS, then the default parameters should let it may not make much difference. But if you have some data on frost mortality, you may be able to better constrain these parameters.

**Comment by koxingazhu** [comment]
> As far as I know, ED has not been used extensively to simulate frost disturbance. Were you expecting defoliation or mortality? For mortality, look at the plant_min_temp and frost_mort in ed_params.f90. They are quite low for most trees, thus mortality is unlikely. I don't think ED2 includes frost defoliation.
> 
> You will likely see larger effects with droughts, which ED has been used to simulate in multiple papers.

Thank you. I just want to simulate extreme climate impact on tree mortality and productivity, but not defoliation. I also look at the plant_min_temp and frost_mort in ed_params.f90. The simulation output showed GPP decreased obviously under frost scenario compared with baseline climate, but the mortality seemed to be unchanged.  Under the drought condition (decreasing precipitation rate in met forcing), simulation results were similar with frost in my study site (a subtropical forest in China).

**Comment by koxingazhu** [comment]
> Just to follow up on Erik's correct comment, the frost mortality model is rather simple: if I remember correctly, it's briefly described in [Albani et al. (2006)](https://dx.doi.org/10.1111/j.1365-2486.2006.01254.x), which is back in ED1 days.
> 
> I think their original idea was to prevent southern pines to live too far north, but if you are simulating hardwoods in the CONUS, then the default parameters should let it may not make much difference. But if you have some data on frost mortality, you may be able to better constrain these parameters.

Thank you. I have found the frost-induced mortality equation in papers Albani et al.  (2006), Longo et al. (2019a) appendix and mortality.f90. The simulation in my project was carried out at a subtropical coniferous forest plantation in Central China. The modeling results showed decreasing GPP under frost condition compared with baseline scenario, but not the case for the mortality.  Maybe I can conclude that frost could impact forest growth (e.g., productivity) obviously, but not mortality.
