### ISSUE TITLE
Default plot size for near bare ground simulation (NL%IED_INIT_MODE = 0)

### ISSUE THREAD

**Issue by koxingazhu** [EDmodel/ED2#329]
Hi, everyone. I carried out a spin-up simulation (NL%IED_INIT_MODE = 0) from 1500 to 2000 to investigate the plant community dynamics at equilibrium. I want to know and how to modify  the default area (i.e., plot size in m^2) for the near bare ground site? Thanks.

**Comment by mdietze** [comment]
ED2 is spatially-implicit, it doesn't have a plot area. The nearest analog would be the parameters controlling cohort and patch fusion and fission (i.e. when ED2 lumps vs splits individual cohorts, and when it lumps vs splits individual patches). These would control the number of cohorts in a patch and the number of patches in a site.

**Comment by larsonej** [comment]
The patches in ED are statistically representative of the vegetation in an area that has the soil type and meteorology that you specify. This could be a very small area if the soil or met is very spatially heterogenous, or a very large area if they not.

**Comment by koxingazhu** [comment]
@mdietze @larsonej Thank you for your responses. I see. ED2 doesn't have a plot area! I checked the ED2IN file and I am sure that NL%MAXPATCH and NL%MAXCOHORT controlling cohort and patch fusion and fission. Maybe I think the unit information  (turn on NL%ATTACH_METADATA for getting them) for different variables in *.h5 output file can help me understand it. For example,  if I want to calculate the aboveground biomass [kgC/m2], I don't need to obtain the "plot area" when I obtained AGB_CO [kgC/plant] and NPLANT [plant/m2].
`library(rhdf5)
file <- "F:\\analy-Y-1583-00-00-000000-g01.h5"
PFT <- h5read(file, "PFT")
AGB_CO <- h5read(file, "AGB_CO") # Units: [kgC/plant]
NPLANT <- h5read(file, "NPLANT") # Units: [plant/m2]
PFT.Cohort <- cbind(PFT, AGB_CO, NPLANT)
as.data.frame(PFT.Cohort) -> df.PFT.Cohort
df.PFT.Cohort$AGB <- df.PFT.Cohort$AGB_CO * df.PFT.Cohort$NPLANT # Units: [kgC/m2]
total.agb <- sum(df.PFT.Cohort$AGB) # Units: [kgC/m2]`

**Comment by koxingazhu** [comment]
@mdietze @larsonej Thank you for your responses. I see. ED2 doesn't have a plot area! I checked the ED2IN file and I am sure that NL%MAXPATCH and NL%MAXCOHORT controlling cohort and patch fusion and fission. Maybe I think the unit information (turn on NL%ATTACH_METADATA for getting them) for different variables in *.h5 output file can help me understand it. For example, if I want to calculate the aboveground biomass [kgC/m2], I don't need to obtain the "plot area" when I obtained AGB_CO [kgC/plant] and NPLANT [plant/m2] from output file.
library(rhdf5)
file <- "F:\\analy-Y-1583-00-00-000000-g01.h5"
PFT <- h5read(file, "PFT")
DBH <- h5read(file, "DBH") # Units: [cm]
AGB_CO <- h5read(file, "AGB_CO") # Units: [kgC/plant]
NPLANT <- h5read(file, "NPLANT") # Units: [plant/m2]
PFT.Cohort <- cbind(PFT, AGB_CO, DBH, NPLANT)
as.data.frame(PFT.Cohort) -> df.PFT.Cohort
df.PFT.Cohort$AGB <- df.PFT.Cohort$AGB_CO * df.PFT.Cohort$NPLANT # Units: [kgC/m2]
total.agb <- sum(df.PFT.Cohort$AGB) # Units: [kgC/m2]
