### ISSUE TITLE
Wrong time sequence in .out file

### ISSUE THREAD

**Issue by Lo-hatch** [EDmodel/ED2#330]
No warning or error, but the content in out.file is strange--
1. repeated line with the same content (the content is supposed to occur only once. I guess?)
2. the printed timestamp  is not in correct sequence. e.g.
- Simulating:   06/29/1997 00:00:00 UTC
 - Simulating:   06/26/1997 00:00:00 UTC
 - Simulating:   06/26/1997 00:00:00 UTC
 - Simulating:   06/30/1997 00:00:00 UTC
 - Simulating:   06/26/1997 00:00:00 UTC
 - Simulating:   06/27/1997 00:00:00 UTC
 - Simulating:   06/30/1997 00:00:00 UTC
 - Simulating:   06/27/1997 00:00:00 UTC
 - Simulating:   06/25/1997 00:00:00 UTC
 - Simulating:   06/27/1997 00:00:00 UTC
 - Simulating:   06/27/1997 00:00:00 UTC
 - Simulating:   06/27/1997 00:00:00 UTC
[test.9669923.a4u03n05.txt](https://github.com/EDmodel/ED2/files/6670177/test.9669923.a4u03n05.txt)

**Comment by Lo-hatch** [comment]
And this is my ED2IN file
[ED2IN_test3.txt](https://github.com/EDmodel/ED2/files/6670339/ED2IN_test3.txt)

**Comment by mdietze** [comment]
It looks like either that you have multiple patches running in parrallel in a single job, or multiple jobs all writing to the same log file.  Given some of the duplicated sections in the log, I'd guess the latter (e.g. you might have accidentally sent the same run to the queue multiple times in quick succession)

**Comment by Lo-hatch** [comment]
> It looks like either that you have multiple patches running in parrallel in a single job, or multiple jobs all writing to the same log file. Given some of the duplicated sections in the log, I'd guess the latter (e.g. you might have accidentally sent the same run to the queue multiple times in quick succession)

Thanks for your help. But I don't know how to check that possible problem. 
I upload my **jobs submit .sh file**, could you please check that for me? Thanks a lot!
[submit_test3.txt](https://github.com/EDmodel/ED2/files/6670471/submit_test3.txt)

**Comment by xiangtaoxu** [comment]
@Lo-hatch I agree with Mike that it is likely because multiple simulations are writing to the same output file. How many simulations you have submitted before getting the output file? Is this error reproducible if you submit **one** new simulation with a different output file name?

**Comment by Lo-hatch** [comment]
@xiangtaoxu @mdietze. Thanks for your suggestion. It turns out to be the problem of my job submit .sh file.
I wrongly assign multiple task for one node (natsk-per-node=10) whereas my single site simulation only requires one task.
So far It seems that the repeated problem as well as the time sequence problem has been solved!
