### ISSUE TITLE
little mistake about the unit description in the output file

### ISSUE THREAD

**Issue by Lo-hatch** [EDmodel/ED2#342]
The output file says the unit of "MMEAN_NPPDAILY_CO" is **kgC m-2 yr-1**, but is not true. It should be **kgC plant-1 yr-1**, the same as "MMEAN_NPP_CO". The problem exist for other variables, e.g. MMEAN_NPPCROOT_CO, MMEAN_NPPCBARK_CO.
However, the unit-- **kgC m-2 yr-1** is right for polygon-level variables, e.g. MMEAN_NPPDAILY_PY

**Comment by xiangtaoxu** [comment]
Thanks! I will label this issue and include the update in the next PR.

**Comment by Lo-hatch** [comment]
> Thanks! I will label this issue and include the update in the next PR.

OK!

**Comment by mpaiao** [comment]
Thanks @Lo-hatch, I just checked the code again, and the units are indeed incorrect for cohort-level variables and should be as you described.  It seems @xiangtaoxu will include the necessary edits in the next PR, but if you are familiar with the source code, feel free to submit a PR with the edits too.

**Comment by Aariq** [comment]
Seems like this hasn't been fixed still.  The incorrect units caused me a lot of confusion.  I'd submit a PR, but I can't figure out where in the ED2 code the metadata is written.

**Comment by Lo-hatch** [comment]
> 
It was written in src\memory\ed_state_vars.F90, e.g.
 call metadata_edio(nvar,igr, 'Monthly mean - Net primary productivity - Fine root'  ,'[  **kgC/m2/yr**]','(icohort)'  )

I think it could work by changing the text here. @Aariq
