### ISSUE TITLE
question about unit in reproduction.f90

### ISSUE THREAD

**Issue by Lo-hatch** [EDmodel/ED2#351]
the calculation of nplant of new recruitment cohort is as:
rectest%nplant    = csite%**repro**(ipft,ipa) / **biomass**
In my opinion, the units of "**repr**o" and "**biomass**" are "kgC m-2 polygon yr-1" and "kgC plant-1",
so the unit of "nplant" is "plant m-2 polygon".
However, the unit of "NPLANT" in ED should always be "plant m-2 patch" ? 
Is that a mistake or I misunderstand the units of these variables?

The link is the relevant code block:
https://github.com/EDmodel/ED2/blob/master/ED/src/dynamics/reproduction.f90#:~:text=rectest%25nplant,rectest%25bstorage)

**Comment by mpaiao** [comment]
Just for future reference, if a patch-level variable (csite%variable(...,ipa)) has m-2 in its units, then you can always assume that it is "m-2(patch)".  

The only exception is csite%area(ipa), which has units of m2(patch) m-2(site).  Likewise, cpoly%area(isi) has units of m2(site) m-2(polygon).

**Comment by Lo-hatch** [comment]
@mdietze @mpaiao Thank you very much! I misunderstood the unit of repro.
