### ISSUE TITLE
`HYDAULIC_MORTALITY_SCHEME` missing from ED2IN

### ISSUE THREAD

**Issue by Aariq** [EDmodel/ED2#358]
Using the development version of of PEcAn.ED2 with the development version of ED2 results in some errors about missing variables.  The ED2IN file in PEcAn.ED2 needed updating (see https://github.com/PecanProject/pecan/pull/3032).  However, there is one missing variable warning that corresponds to a variable not in the ED2IN file in ED2/ED/run/ED2IN: 

```
------------------------------------------------------
>>>>  opspec_misc  error! in your namelist!
    ---> Reason:      Invalid HYDAULIC_MORTALITY_SCHEME, it must be between 0 and 1. Yours is set to -999...
------------------------------------------------------
```

Not sure, but I think this means the ED2IN file is out of date.

**Comment by xiangtaoxu** [comment]
I think this is because of a typo in PEcAN.ED2. It should be HYD**R**AULIC_MORTALITY_SCHEME. An R is missing in your case

**Comment by Aariq** [comment]
aahh, wow 🤦‍♂️ I did not notice that.

**Comment by Aariq** [comment]
Actually that typo is in ED2: https://github.com/EDmodel/ED2/blob/125f814dbbd7c258cf623254ca9554a7e59807fd/ED/src/io/ed_opspec.F90#L1998

But that does explain why I didn't find it in the ED2IN—I was searching for the typo version.

**Comment by Aariq** [comment]
PR for typos here: https://github.com/EDmodel/ED2/pull/360
