### ISSUE TITLE
Do not add your *.mod files to Git repository

### ISSUE THREAD

**Issue by apourmok** [EDmodel/ED2#36]
I am not sure if anyone else is running to the same problem or not but *.mod files in .build/bin should not be added to git repository since they will be created during compilation. Adding them causes issue that every time you want to switch between branches or commit or pull upstream, you need to remove them manually.

**Comment by DanielNScott** [comment]
They should all be explicitly in the .gitignore...

Mine has:
```sh
# very general rules to ignore files in bin folder
*/bin/*.c
*/bin/*.mod
*/bin/*.[fF]90
*/cs6_build/bin/*.c
*/cs6_build/bin/*.mod
*/cs6_build/bin/*.[fF]90

*/cs6_build/bin/slurm-*
*/cs6_build/bin/qinst.out
*/cs6_build/bin/qinst.err
*/cs6_build/ed_2.1-*
```

**Comment by apourmok** [comment]
True but every time I do pull upstream master or re compile the model, I end up having the same problem despite already ignoring them.

**Comment by DanielNScott** [comment]
Huh, interesting. That's a pain, I don't know why it would be. Upstream master is set to this repository, not your fork? And your fork has all that in the git ignore? It looks like this repository's git ignore is set properly.

**Comment by rgknox** [comment]
yeah, I think it is curious too.  Afshin, do you get the .mod files if you
make a completely new clone?

**Comment by apourmok** [comment]
@DanielNScott and @rgknox, so I made a new clone and the problem is solved. Somehow those files got in to my repository! So I guess I am going to close this issue. Thanks for your help.
