### ISSUE TITLE
hdf5 problem when running HISTORY mode

### ISSUE THREAD

**Issue by Lo-hatch** [EDmodel/ED2#363]
when I run INITIAL mode, everything is normal. However, when I run HISTORY based on the history file of the initial simulation: 
    ---> File:        h5_output.F90
    ---> Subroutine:  h5_output
    ---> Reason:      Failed creating the HDF file
    ---> File:        h5_output.F90
    ---> Subroutine:  h5_output
    ---> Reason:      Failed creating the HDF file
And the reason is :
fatal_error
HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: H5F.c line 520 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1085 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 275 in H5F_super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
fatal_error
**And even though it reports error, it still can generate the output files, but takes much longer time!**

**Comment by Lo-hatch** [comment]
my ED2IN file and the log file.
[ED2IN_history.txt](https://github.com/EDmodel/ED2/files/9694351/ED2IN_history.txt)
[hisTESTout.txt](https://github.com/EDmodel/ED2/files/9694356/hisTESTout.txt)

**Comment by koxingazhu** [comment]
I often set the NL%SFILIN same as NL%SFILOUT when running HISTORY, because history file was generated in NL%SFILOUT by default.
I find your NL%SFILIN is not the same as NL%SFILOUT. Are you sure that the history file (i.e., histo-S-2000-01-01-000000-g01.h5?) was copied from NL%SFILOUT to NL%SFILIN?

**Comment by Lo-hatch** [comment]
> 



> 
Thanks. my SFILOUT is not the same as SFILIN, but I find it's ok to set different path. Somehow, after I changed some settings, the problem disappeared. The success version still support different SFILOUT and SFILIN.

**Comment by Lo-hatch** [comment]
> I often set the NL%SFILIN same as NL%SFILOUT when running HISTORY, because history file was generated in NL%SFILOUT by default. I find your NL%SFILIN is not the same as NL%SFILOUT. Are you sure that the history file (i.e., xsbn-S-2000-01-01-000000-g01.h5?) was copied from NL%SFILOUT to NL%SFILIN?

Thanks. my SFILOUT is not the same as SFILIN, but I find it's ok to set different path. Somehow, after I changed some settings, the problem disappeared. The success version still support different SFILOUT and SFILIN.

**Comment by Lo-hatch** [comment]
**the failure version**: the SFILOUT path is two level below the path where I posit the .sh file
e.g. I sbatch the .sh file to run ED2 in /path1, and generate output files in /path1/path2/path3/*.h5
**the success version:**
e.g.  I sbatch the .sh file to run ED2 in /path1, and generate output files in /path1/path2/*.h5 
**sounds not like a reasonable explanation, but I have not found other clues yet.**
