### ISSUE TITLE
Uninitialized variable Clean-Up

### ISSUE THREAD

**Issue by crollinson** [EDmodel/ED2#37]
While helping debug the SMP issues ( #30 ), I've discovered there are currently 5 cases of uninitialized variables in the mainline branch and would appreciate some help tracking them down so we can document in the code that this is okay or fix them (preferable):

1) rk4_misc.f90: In function 'adjust_sfcw_properties':
rk4_misc.f90:1565: warning: 'depth_available' may be used uninitialized in this function

2) ed_state_vars.f90: In function 'copy_sitetype_mask':
ed_state_vars.f90:8795: warning: 'i' may be used uninitialized in this function

3) ed_read_ed21_history.F90: In function 'read_ed21_history_file':
ed_read_ed21_history.F90:447: warning: 'si_index' may be used uninitialized in this function

4) heun_driver.f90: In function 'heun_stepper':
heun_driver.f90:807: warning: 'combh' may be used uninitialized in this function

5) events.f90: In function 'event_irrigate':
events.f90:649: warning: 'soil_temp' may be used uninitialized in this function

1) I have tracked down and solved the first one.  (see #30 )

2) This stems from a change by @mpaiao on I think 14 November 2012 (commit 37188deef5445bcc76391a147646396722d12eee).  Marcos, I can't quite figure out what's going on here (probably just me not understanding the syntax).  If what I think is happening is right, this actually isn't a problem, but it'd be great if you could double check.

3) @rgknox I think this one might come in from one of your commits (circa June 2012) based a quick scan of the history on that file. Could you maybe take a glance to see if you can figure out what's going on?

I haven't looked into 4 or 5 yet, but if somebody knows who added the irrigation or worked on the heun stepper, it'd be great if they could help fill in the gaps.

**Comment by mdietze** [comment]
Heun is probably @rgknox 
events file is my code (and 99% chance it's my bug), but @apourmok has been working on that much more recently so I'm hoping he can help you fit it.

**Comment by mpaiao** [comment]
I will check items 2-4 later today, they are all likely to be my bugs...

**Comment by rgknox** [comment]
will look into 3) as well
Christy, what version are you currently testing and working with?  ED2 master, or your branch?

**Comment by rgknox** [comment]
wow, just wow.  I will have to see when this bug was created.


si_index should be initialized first thing within the siteloop on L377 of ed_read_ed21_history.F90 like so:

siteloop: do isi=1,pysi_n(py_index)

si_index = pysi_id(py_index) + isi - 1

**Comment by crollinson** [comment]
I'm working off of my master branch which is the ED2 mainline master + the CBR fixes from the standing. It should be what was submitted for the pull request.

**Comment by crollinson** [comment]
(In response to Ryan's comment about the Heun Driver in #30 )

I just went back to the very first commit with the heun driver (a066d0e26f7997dd016a9b2e5ac8d77f49412221) and found this in Line 772 : 
   combh = heun_b21*h 

@mpaiao I'm not sure when this disappeared, but since you seem to be the one who put it there first place & have done most the work since, can you confirm that this is still the proper initialization?

**Comment by crollinson** [comment]
and I just took a glance at # 5 on the list.  Haven't traced the history, but it looks like making soil_tempk equal to that patch's surface soil temp would be totally reasonable.

**Comment by mpaiao** [comment]
@crollinson it is, but we don't need the derivatives of can_prss, we could delete lines 807-808 and 863-865.  These are parts of a very old test and somehow survived in the code up to now, possibly because no one is using Heun.  

Heun is a RK2 method, and I implemented it to try a faster version of RK4 but it turned out to be slower.  I agree with @rgknox, and I think we should delete it for good.
