### ISSUE TITLE
typo in calc_plant_water_flux

### ISSUE THREAD

**Issue by Lo-hatch** [EDmodel/ED2#389]
when calculating wood_psi, the **bp** term should be: 
         bp = (weighted_soil_psi * **weighted_gw_cond**   - wflux_wl_d) / c_stem ! m/s
rather than:
         bp = (weighted_soil_psi - wflux_wl_d) / c_stem ! m/s
https://github.com/EDmodel/ED2/blob/master/ED/src/dynamics/plant_hydro.f90#:~:text=bp%20%3D%20(weighted_soil_psi%20%2D%20wflux_wl_d)%20/%20c_stem%20!%20m/s

**Comment by xiangtaoxu** [comment]
why is `weighted_gw_cond` necessary?

gw_cond is already considered when calculated weighted_soil_psi
https://github.com/EDmodel/ED2/blob/b9c93f806d6df7a38db306d944a0695d8b40b39a/ED/src/dynamics/plant_hydro.f90#L845

**Comment by Lo-hatch** [comment]
> why is `weighted_gw_cond` necessary?
> 
> gw_cond is already considered when calculated weighted_soil_psi
> 
> https://github.com/EDmodel/ED2/blob/b9c93f806d6df7a38db306d944a0695d8b40b39a/ED/src/dynamics/plant_hydro.f90#L845

oh, yes, I didn't notice that
