### ISSUE TITLE
Issue with compilation in a server

### ISSUE THREAD

**Issue by utlacs** [EDmodel/ED2#397]
Hi. I am trying to compile ED model in a server of Compute Canada. I read the documentation of ED model. I have made the include.mk file. But unable to compile. I am getting this error:
 module hdf5_coms
   use hdf5

   integer(HID_T) :: dsetid_f,dspaceid_f,fileid_f,prpid_f
   integer(HID_T) :: plist_id,file_id,dset_id,filespace,memspace,dspace_id

   integer(HSIZE_T),dimension(6) :: globdims,chnkdims,chnkoffs
   integer(HSIZE_T),dimension(6) :: cnt,stride

   integer(HSIZE_T),dimension(6) :: memsize,memdims,memoffs !EQUIV IN MEM

   integer(HID_T)  :: datatype_id ! Datatype identifier 
   integer(SIZE_T) :: setsize  ! Datatype size
end module hdf5_coms hdf5_coms.f90(7): error #6683: A kind type parameter must be a compile-time constant.   [HSIZE_T]
   integer(HSIZE_T),dimension(6) :: globdims,chnkdims,chnkoffs
-----------^
hdf5_coms.f90(8): error #6683: A kind type parameter must be a compile-time constant.   [HSIZE_T]
   integer(HSIZE_T),dimension(6) :: cnt,stride
-----------^
hdf5_coms.f90(10): error #6683: A kind type parameter must be a compile-time constant.   [HSIZE_T]
   integer(HSIZE_T),dimension(6) :: memsize,memdims,memoffs !EQUIV IN MEM
-----------^
hdf5_coms.f90(12): error #6683: A kind type parameter must be a compile-time constant.   [HID_T]
   integer(HID_T)  :: datatype_id ! Datatype identifier 
-----------^
hdf5_coms.f90(13): error #6683: A kind type parameter must be a compile-time constant.   [SIZE_T]
   integer(SIZE_T) :: setsize  ! Datatype size
-----------^
compilation aborted for hdf5_coms.f90 (code 1)
make[1]: *** [rules.mk:314: hdf5_coms.o] Error 1
make[1]: Leaving directory '/lustre06/project/6075933/utlacs/ED2-v.2.2.0/ED/build/bin-opt-E'
make: *** [Makefile:63: all] Error 2
[includemkfile.docx](https://github.com/EDmodel/ED2/files/12468946/includemkfile.docx)
Please help.

**Comment by xiangtaoxu** [comment]
Looks like your HDF5 library is not properly configured. Please make sure you have the hdf5 library in the path specified makefile and it was compiled with the same compiler as you are using.

**Comment by utlacs** [comment]
> Looks like your HDF5 library is not properly configured. Please make sure you have the hdf5 library in the path specified makefile and it was compiled with the same compiler as you are using.

I have downloaded from HDF5 website and use these steps to configure: 
tar -zxvf hdf5-1.10.10.tar.gz
cd hdf5-1.10.10
./configure --prefix=/ED2-v.2.2.0/LIBRARIes/hdf5
make
make check
make install

**Comment by xiangtaoxu** [comment]
Hmm... It's been a while since I configure hdf5 for ED2.... Do you have cluster support staff? They are more familiar with cluster-specific usages of these packages.

Maybe others who have recent experiences of compiling ED2 can chime in....

**Comment by utlacs** [comment]
Thank you for your help in suggesting that I configured correctly. I compiled it with the following configuration: ./configure --prefix=/home/*****/hdf5 --enable-fortran. And in paths of directories I have given like this ZLIB_PATH= /home/***/zlib/1.2.8
HDF5_PATH= /home/****/hdf5
HDF5_INCS= -I$(HDF5_PATH)/include
HDF5_LIBS= -L$(HDF5_PATH)/lib -lhdf5 -lhdf5_fortran -lhdf5_hl
