### ISSUE TITLE
Too many open files - HDF5 error

### ISSUE THREAD

**Issue by rgknox** [EDmodel/ED2#4]
My test cases are not properly closing HDF5 files during read and/or writes.  

If anyone has a potential solution or can re-create this issue, please comment.

My system is a GNU linux, gfortran 4.8 compiler, and HDF5 1.8.13.  I have also reproduced this issue with HDF5 1.8.11 and gfortran 4.6.

Here is an example of the complaint:

HDF5-DIAG: Error detected in HDF5 (1.8.13) thread 0:
  #000: H5F.c line 1594 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5F.c line 1290 in H5F_open(): unable to open file: time = Sat Jul 12 19:56:45 2014
, name = '/home/rgknox/Datasets/m34_tower_manzi/ed_drivers/KM34_EDM2.2_30MIN_2008NOV.h5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 985 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = '/home/rgknox/Datasets/m34_tower_manzi/ed_drivers/KM34_EDM2.2_30MIN_2008NOV.h5', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
    Error opening hdf5 file - error -          -1

**Comment by rgknox** [comment]
This problem has been fixed, thanks Toni.  Closing issue.

**Comment by RizhaoCai** [comment]
> This problem has been fixed, thanks Toni. Closing issue.

Hello, how did you fix it?
