### ISSUE TITLE
Problem with compiling due to radiate_driver.f90

### ISSUE THREAD

**Issue by apourmok** [EDmodel/ED2#43]
I pulled the latest main line changes in to my local branch and when I try to compile the code, I keep getting the error message below (I already tried ./install.sh clean) which is related to radiate_driver.f90 file, any thoughts what is causing it?

Error: Expecting END IF statement at (1)
radiate_driver.f90:1067.3:

end subroutine sfcrad_ed
   1
Error: Expecting END IF statement at (1)
radiate_driver.f90:1080.4:

real function ed_zen(plon,plat,when)
    1
Error: 'real' at (1) is not a variable
radiate_driver.f90:1081.55:

   use ed_misc_coms , only : simtime      ! ! structure
                                                       1
Error: Unexpected USE statement at (1)
radiate_driver.f90:1085.56:

                           , tiny_num8    ! ! intent(in)
                                                        1
Error: Unexpected USE statement at (1)
radiate_driver.f90:1086.16:

   implicit none
                1
Error: Unexpected IMPLICIT NONE statement at (1)
radiate_driver.f90:1088.36:

   real(kind=4) , intent(in) :: plon
                                    1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1089.36:

   real(kind=4) , intent(in) :: plat
                                    1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1090.16:

   type(simtime), intent(in) :: when
                1
Error: Derived type 'simtime' at (1) is being used before it is defined
radiate_driver.f90:1092.68:

   integer                   :: doy     ! Day of year ("Julian" day)
                                                                    1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1093.53:

   real(kind=8)              :: declin  ! Declination
                                                     1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1094.61:

   real(kind=8)              :: sdec    ! Sine of declination
                                                             1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1095.63:

   real(kind=8)              :: cdec    ! Cosine of declination
                                                               1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1096.54:

   real(kind=8)              :: dayhr   ! Hour of day
                                                      1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1097.61:

   real(kind=8)              :: radlat  ! Latitude in radians
                                                             1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1098.61:

   real(kind=8)              :: clat    ! Cosine of latitude
                                                             1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1099.58:

   real(kind=8)              :: slat    ! Sine of latitude
                                                          1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1100.64:

   real(kind=8)              :: dayhrr  ! Hour of day in radians
                                                                1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1101.52:

   real(kind=8)              :: hrangl  ! Hour angle
                                                    1
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1103.85:

nd=8), parameter   :: capri    = -2.344d1 ! Tropic of Capricornium latitude
                                                                           1                                                                                                   
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1104.92:

parameter   :: ndaysnl  =  3.65d2  ! Number of days of year (no leap years)
                                                                           1                                                                                                   
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1105.89:

), parameter   :: ndayslp  =  3.66d2  ! Number of days of year (leap years)
                                                                           1                                                                                                   
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1106.87:

   , parameter   :: shsummer = -10      ! DoY of Southern Hemisphere summer
                                                                           1                                                                                                   
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1108.85:

     , external    :: julday  ! Function to find day of year ("Julian" day)
                                                                           1                                                                                                   
Error: Unexpected data declaration statement at (1)
radiate_driver.f90:1109.88:

  , external    :: isleap  ! Function to determine whether the year is leap
                                                                           1                                                                                                   
Error: Unexpected data declaration statement at (1)
Fatal Error: Error count reached limit of 25.
make[1]: *** [radiate_driver.o] Error 1
make[1]: Leaving directory `/usr2/postdoc/apourmok/ED2-1/ED/build/bin'
make: *** [all] Error 2

**Comment by crollinson** [comment]
Afshin, it looks like before the part you pasted there's a missing close of a loop or IF statement. It looks to probably somewhere in the radiate driver, but since I'm not having any issues, it might be a missing END IF or END DO statement in one of your modifications.  Did you modify the radiate driver at all?  If you can either paste the compile output form a bit further up or just copy save the entire compile output and email it to me and I'll see if I can figure out where the bug is?

**Comment by apourmok** [comment]
Resolved the issue by reverting commits. Thanks.
