### ISSUE TITLE
Error compiling RAPP, different character lengths

### ISSUE THREAD

**Issue by fabeuw** [EDmodel/ED2#53]
I can't see to compile mod_ncep.f90, neither via make neither manually, in both cases I get the same error. I checked online and some mention to pad the string length by adding extra character, I tried that but with no result. Does anybody have an idea what might be causing this?

mpif90 -O3 -ffree-line-length-none  -fno-whole-file  -I/usr/include  -c mod_ncep.f90
OR 
carya@pecan64:~/edf/RAPP/build/bin$ gfortran -o mod_ncep -I/usr/include mod_ncep.f90 -L/usr/lib64 -lnetcdff -lnetcdf -lhdf5 -lm -lhdf5_fortran -lhdf5 -lhdf5_hl -lz
mod_ncep.f90:61.25:

                        , 'pres'             & ! Pressure                      
                         1
Error: Different CHARACTER lengths (3/4) in array constructor at (1)
mod_ncep.f90:81.54:

                (/ 'air.sig995/air.sig995'           , 'pres.sfc/pres.sfc'     
                                                      1
Error: Different CHARACTER lengths (21/17) in array constructor at (1)
mod_ncep.f90:108.25:

                        , 'pres'             & ! Pressure                      
                         1
Error: Different CHARACTER lengths (3/4) in array constructor at (1)
mod_ncep.f90:118.25:

                        , 'nbdsf'            & ! Near-IR beam radiation        
                         1
Error: Different CHARACTER lengths (3/5) in array constructor at (1)
mod_ncep.f90:126.25:

                        , 'prate'           /) ! Precipitation rate            
                         1
Error: Different CHARACTER lengths (3/5) in array constructor at (1)

**Comment by fabeuw** [comment]
Ok so the issue is that variable names in these arrays are of different length. I have been suggested to add spaces to make them the same length and then use the fuction trim. However I am not sure where to place such function within the RAPP code.

**Comment by mpaiao** [comment]
@fabeuw I quickly checked the code, and I think you are right, it looks like all places that should have trim already have it.  I wrote these routines several years ago, and I was unaware that this syntax was deprecated.  I compiled with ifort 10 back then and it didn't complain, but it's actually quite common for deprecated syntax to work with some compilers and crash with others, we had similar problems in the main ED code several times.

**Comment by fabeuw** [comment]
@mpaiao Thanks, I did in fact add spaces and now it compiles, it should also work but I haven't been able to create rapp_1.0 yet

**Comment by mpaiao** [comment]
I just tried here, and I was able to compile using gfortran (although an old version).  I made a few changes to include.mk and Makefile.  Not sure if they are all necessary, but in any case:

Makefile, near line 65:
```Makefile
$(EXE): $(LIBMODEL) $(MAINOBJ)
	@echo ""
	$(LOADER) -o $(EXE) $(MAINOBJ) $(LOADER_OPTS) $(INCLUDES) $(LIBMODEL) $(ALL_LIBS)
	@echo ""
	@echo Finished building === $(EXE)
	@echo ""
```

include.mk
```Makefile
USE_HDF5=1
HDF5_PATH=/path_to/hdf5-1.8.14/gnu
HDF5_INCS=-I$(HDF5_PATH)/include
HDF5_LIBS=-lm -lz -L$(HDF5_PATH)/lib -lhdf5 -lhdf5_fortran -lhdf5_hl
USE_NCDF=1
NCDF_PATH=/path_to/netcdf-3.6.3/gnu
NCDF_INCS=-I$(NCDF_PATH)/include
NCDF_LIBS=-L$(NCDF_PATH)/lib -lnetcdff -lnetcdf
CMACH=PC_LINUX1
F_COMP=gfortran
C_COMP=gcc
LOADER=gfortran
LIBS=
F_OPTS= -O3 -static -ffree-line-length-none
C_OPTS= -DLITTLE -static -O3 -ffree-line-length-none
LOADER_OPTS=-O3 -ffree-line-length-none
```

**Comment by fabeuw** [comment]
thanks @mpaiao that helped. Should I check in the correct mod_ncep.f90?

**Comment by mpaiao** [comment]
@fabeuw I fixed it in my branch too, so it's in the pending pull request.

**Comment by fabeuw** [comment]
ok great, closing this then.
