### ISSUE TITLE
Variable is not short [RAPP]

### ISSUE THREAD

**Issue by fabeuw** [EDmodel/ED2#57]
I am running RAPP, but when the code checks whether a variable is nf90_short type the execution stops right away processing the first variable 'air'. I don't know why this check is in place, however by opening air and other variables in HDFView it seems the variables are floating 32-bit. According to the netcdf documentation this should be a NF90_FLOAT. Am I missing something? This is the piece of code within the mod_ncdf_globio

elseif (xtype /= NF90_SHORT) then
            call fatal_error('Variable '//trim(varname)//' is not short integer!

**Comment by mpaiao** [comment]
@fabeuw  I checked the routine ncio_2dshort and it looks like back when I wrote the code, the variable was stored as short integer, along with a scale factor and offset, and they probably stored this way to make files smaller.  

It's entirely possible that they have changed the format since then.   Also, I remember you mentioned that you would try to download just the area of interest instead of the global files.  Perhaps the files come in a different format when you download the subset.   Either way, you may need to change the code to read NF90_FLOAT instead of NF90_SHORT, and check whether the offset/scale factors still exist.

**Comment by fabeuw** [comment]
@mpaiao I downloaded the global grids so indeed they are now float. There doesn't seem to be any offset or scalar factor, should we update the code that deals with that as well, or given that it won't find those values it shouldn't do anything? 
I have changed that if statement now, and the NF90_SHORT is also in ncep_fill_infotable.f90. Do you want to add these pull these changes as well? Although I think there might be other issues. Because now the routine stops at 'pres' with the following error 
    - Loading the NCEP variables...
         [|] Retrieved : air . Range: [  0.0000000E+00 :  1.4553330E-29 ] . # missing:       0.
         [|] While retrieving : pres ...
           [!] netCDF error reading the variable!
           [!] Message: NetCDF: Numeric conversion not representable...
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
---------------------------------------------------------------
                    !!! FATAL ERROR !!!                        
---------------------------------------------------------------
    ---> File:        mod_ncdf_globio.F90
    ---> Subroutine:  ncio_2dshort
    ---> Reason:      Error retrieving the variable pres...
---------------------------------------------------------------
 MEVI execution halts (see previous error message)..

the relevant code

!----- Guess it's okay to get the variable now -----------------------------------!
         else
            ierr = nf90_get_var(ncid,varid,tmpvar,start=start,count=count,stride=stride)
            if (ierr /= NF90_NOERR) then
               write (unit=*,fmt='(2(a,1x),a)')                                            &
                  '         [|] While retrieving :',trim(varname),'...'
               call ncdf_load_err(ierr)
               call fatal_error ('Error retrieving the variable '//trim(varname)//'...'    &
                                ,'ncio_2dshort','mod_ncdf_globio.F90')
            end if


From my research it seems that it's caused by some kind of inconsistencies with data size 4bytes vs 8bytes. But I am not sure which variable in pres is causing this error, is it pres itself or time?

**Comment by mpaiao** [comment]
@fabeuw Temperature doesn't look right  either, I think the numbers between the square brackets are supposed to be the the minimum and maximum.  

Did you change the variable declaration for tmpvar from integer(kind=2) to real(kind=4)? If not, then this could explain the weird values/crashes.  Also,  If offset and scale are no longer applicable then just skip the part of the code that obtains the offset and scale factor and set them to 0 and 1 respectively.

**Comment by fabeuw** [comment]
@mpaiao ok I think that was the issue, It seems it's working now. I did not comment anything, I just assigned 0 and 1 to the two variables right after
```
 ierr = nf90_get_att(ncid,varid,'missing_value',missshort)
    ierr = nf90_get_att(ncid,varid,'add_offset'   ,refval   )
     ierr = nf90_get_att(ncid,varid,'scale_factor' ,scalefac ) 
```

I was getting mostly 0 in my h5 files but I forgot to set offset and scale factor, when I did that this is what I got.

```
- Loading the NCEP variables...
         [|] Retrieved : air . Range: [  1.9439999E+02 :  3.2110001E+02 ] . # missing:       0.
         [|] Retrieved : pres . Range: [  5.0280000E+04 :  1.0952000E+05 ] . # missing:       0.
         [|] Retrieved : rhum . Range: [  1.0000000E+00 :  1.0000000E+02 ] . # missing:   78341.
         [|] Retrieved : uwnd . Range: [ -2.9000000E+01 :  3.2500000E+01 ] . # missing:    8676.
         [|] Retrieved : vwnd . Range: [ -2.6899994E+01 :  2.8699997E+01 ] . # missing:    9917.
         [|] Retrieved : pres . Range: [  8.4340000E+04 :  1.0289000E+05 ] . # missing:       0.
         [|] Retrieved : dlwrf . Range: [  2.4700000E+02 :  4.7800000E+02 ] . # missing:       0.
         [|] Retrieved : nbdsf . Range: [  1.0000000E+00 :  3.7600000E+02 ] . # missing:    7171.
         [|] Retrieved : nddsf . Range: [  1.0000000E+00 :  3.2600000E+02 ] . # missing:    6951.
         [|] Retrieved : vbdsf . Range: [  1.0000000E+00 :  4.0100000E+02 ] . # missing:    7875.
         [|] Retrieved : vddsf . Range: [  1.0000000E+00 :  4.4000000E+02 ] . # missing:    6394.
         [|] Retrieved : prate . Range: [  9.9977478E-07 :  5.9899990E-04 ] . # missing:   16665.
```
And the h5 variables now look like some legit numbers. Do you want to pull this update as well? I could send you the if you want. I am wondering if we should make RAPP work with the Reanalysis 2.

**Comment by mpaiao** [comment]
@fabeuw Great that it's working now, the numbers look reasonable. I think it makes more sense if you submit the pull request since you fixed it; the other fix went with my pull request just because I was trying to reproduce your error here.

I think the more datasets RAPP is able to process the better. I won't have time to work directly on it, but I'm happy to help where I can.
