### ISSUE TITLE
Tips for zoobukhov8 convergence?

### ISSUE THREAD

**Issue by crollinson** [EDmodel/ED2#58]
One of my sites is having trouble with zoobukhov8 convergence.  I've tried a number of things, including cranking down the time step, but can't get it to go through.  I'm running with ISFCLYRM = 4, but have tried the others that don't require starting from an initial state again. (I'm trying to avoid having to start over and lose the 500 years I've already run).

Here's what the print statement says when it crashes:

-------------------------------------------------------
 Zeta finding didn't converge!!!
 I gave up, after    60 iterations...
 
 Input values.
 
rib             [   ---] =       0.0000
ribuse          [   ---] =       0.0000
zstar           [     m] =       4.6240
rough           [     m] =       5.0528
zoz0m           [   ---] =       0.9152
lnzoz0m         [   ---] =      -0.0887
zoz0h           [   ---] =       0.9152
lnzoz0h         [   ---] =      -0.0887
stable          [   T|F] = F
 
 Last iteration outcome (zoobukhov8 values).
zetaa           [   ---] =       0.0001
zetaz           [   ---] =      -0.0000
fun             [   ---] =      -0.0000
fm              [   ---] =      -0.0887
fh              [   ---] =      -0.0887
funa            [   ---] =      -0.0000
funz            [   ---] =       0.0001
deriv           [   ---] =      -1.0000
toler           [   ---] =   1.1921E-06
error           [   ---] =   4.7418E+01
zoobukhov8      [   ---] =       0.0001

-------------------------------------------------------

**Comment by mpaiao** [comment]
@crollinson I don't think the problem is in zoobukhov8; your zstar (reference height - displacement height) is less than roughness, and this should never happen.  Perhaps the reference height of the met driver is too low?  Also, it's odd that the Richardson number is exactly zero in an ongoing simulation (possible, but unlikely)...

**Comment by crollinson** [comment]
Aha, thanks @mpaiao!  My met reference height is set for 30 m, and I had bumped the max height of many of my PFTs to be greater than that (closer to some of actual max heights in the lit) and this was causing it to bonk.   

There is a sanity check on this in the met driver, there must be something in the the order of operations in the reading in of the met driver & the configurations xml so that if you modify b1Ht in the xml, it circumvents this check.  The order in the model output suggests this shouldn't happen, but the bottom line is that we're not getting a sanity error I should have gotten.  This should be a simple fix that I can look into and submit a pull request for.
