### ISSUE TITLE
do I need permission to push some changes?

### ISSUE THREAD

**Issue by fabeuw** [EDmodel/ED2#59]
I am trying to push some changes, only a couple of files inside RAPP, but I get this message. 

remote: Permission to EDmodel/ED2.git denied to fabeuw.
fatal: unable to access 'https://github.com/EDmodel/ED2.git/': The requested URL returned error: 403

I am not sure if I need to be given permission or if I push these to my fork and then open a pull request. Git status tells me I am on the branch master

carya@pecan64:~/edf/RAPP/build/bin$ git status
On branch master

**Comment by mdietze** [comment]
You have to push any changes to your fork and then open a pull request. You're the master of your local copy but not the mainline.
