### ISSUE TITLE
wind speed (vels), ugrd, vgrd, possible conversion error RAPP

### ISSUE THREAD

**Issue by fabeuw** [EDmodel/ED2#62]
My run stops because wind speed turns out to be "infinity". The variable in lapse.f90 is cpoly%met(isi)%vels but I can't find where in the code wind speed is calculated. I checked my data and both vgrd and ugrd have values such as -3.45436E30. And the NCEP original values look fine. So perhaps this is what's causing the infinity value. Maybe something in the NCEP conversion in RAPP went wrong? @mpaiao do you have an idea what might be causing this?

EDIT: vgrd has the same problem.

**Comment by mpaiao** [comment]
@fabeuw I just checked RAPP and it looks like the code is doing the same thing for both uwnd and vwnd, so I can't think of anything obvious.  Did the range that RAPP shows on screen look normal when you ran it?  

If your uwnd is of the order of 10^30, then this is definitely why you got infinity, the maximum number in single precision is about 10^38, and in ED we interpolate kinetic energy (so u^2) instead of the actual wind.  The wind speed is calculated in ED/src/driver/ED_driver.f90.

**Comment by fabeuw** [comment]
@mpaiao good point about checking RAPP, and in fact I see this. When the variable is loaded from the .nc files look OK, then on 1st and 2nd pass I get those crazy values. Are the values calculated in the objective analysis the ones actually saved into the h5 files? I looked at the code but I am not sure how to fix this.

```
[|] Retrieved : uwnd . Range: [ -3.1800003E+01 :  3.1600006E+01 ] . # missing:    9095.
 [|] Retrieved : vwnd . Range: [ -3.1800003E+01 :  2.9199997E+01 ] . # missing:   11301.
```
```
[|] Objective analysis, reference  : Zonal wind        . Range: [ -9.1999969E+00 :  8.0000000E+00 ] . # missing:     193.
         [|] Objective analysis, 1st pass   : Zonal wind        . Range: [ -3.4763319E+00 :  2.9966725E+33 ] . # missing:       0.
         [|] Objective analysis, second pass: Zonal wind        . Range: [ -8.4047981E+32 :  9.1360334E+33 ] . # missing:       0.
         [|] Objective analysis, reference  : Meridional wind   . Range: [ -9.3000031E+00 :  1.0600006E+01 ] . # missing:     136.
         [|] Objective analysis, 1st pass   : Meridional wind   . Range: [ -2.0187542E+00 :  2.3489597E+33 ] . # missing:       0.
         [|] Objective analysis, second pass: Meridional wind   . Range: [ -5.8508895E+32 :  7.6644049E+33 ] . # missing:       0.

```

**Comment by mpaiao** [comment]
@fabeuw I think I found the bug, it looks like the code is trying to interpolate missing values.  Try the following:

Go to function wei_ave (RAPP/src/interp/space_interp.f90)
Add
```fortran
   use mod_ioopts , only : missflg_real  ! ! intent(in)
   implicit none
```
Then inside xloop, replace the if statement by:
```fortran
   if ( (.not. mask(x,y)) .or. var(x,y) == missflg_real) cycle xloop
```


Also, in subroutine oa_2ndpass, inside rtloop:
```fortran
            !------------------------------------------------------------------------------!
            ! 2.c. Compute the "residual".  It is actually what is missing to reach the    !
            !      expected value, and it is simply the difference between the expected    !
            !      and the estimated values.                                               ! 
            !------------------------------------------------------------------------------!
            if (vlola(xl,yl,tt) == missflg_real) then
               interp_buffer%residu(xl,yl,tt) = missflg_real
            else
               interp_buffer%residu(xl,yl,tt) = vlola(xl,yl,tt) - vest
            end if
```

**Comment by fabeuw** [comment]
@mpaiao thanks whiz! that fixes the issue with the wind, but another one arose. Now prate is causing the issue. In the original NCEP data I have a normal range
```
[|] Retrieved : prate . Range: [  9.9977478E-07 :  5.1299995E-04 ] . # missing:   15263.
```
In the processed data I have a some 1.0E34, and when I run ED I get...Although nowhere in the h5 data is see that 2.77778E+32 value. Not sure if it has to do with rain downscaling, however in RAPP_IN I left NL%NDOWNSCAL = 0, also when I tried to set it to 1 the process just got stuck at the downscaling phase.
```
- Simulating:   01/01/1900 00:00:00 UTC
---------------------------------------------------
 Precipitation rate doesn't make sense... 
 
 - Polygon        :      1
 - Site           :      1
 - Date           : 01/01/1900
 - Time           : 18:10:00 UTC
 - Longitude      :  1.80000E+01
 - Latitude       :  0.00000E+00
 - Site Precip    :  2.77778E+32
 - Polygon Precip :  2.77778E+32
 - Minimum OK     :  0.00000E+00
 - Maximum OK     :  1.11100E-01
---------------------------------------------------
```

**Comment by mpaiao** [comment]
@fabeuw To be honest I find odd that the reanalyses have so many missing values, but perhaps I downloaded from a different location... Anyway,  1/3600 = 2.77778e-4, so the error message is just some unit conversion for the output, and the problem is that RAPP is generating files with missing values, which ED doesn't support. 

For a quick fix, go to ncep_loadvars.F90, sub-routine ncep_loadvars, and change the case('prate') by the following:
```fortran
      case ('prate')
         call loadshort(info_table(nv)%filename,vars_ncep(nv),ssxp(ifm),ssyp(ifm)          &
                       ,sstp(ifm),x_1st(ifm),y_1st(ifm),t_1st(ifm),tlast(ifm)              &
                       ,ncep_g(ifm)%prate,ierr)
         where (nceg(ifm)%prate == missflg_real)
            ncep(ifm)%prate = 0.
         end where
```

This is a kludge really, and I guess the radiation terms are going to be the next ones to crash...

**Comment by fabeuw** [comment]
@mpaiao nice prediction :-) radiation I think has the same problem. I need to see what's happening with all these missing values, maybe this region has flaky data. I just don't see all these missing values in the original NCEP data. What if missing value has changed in NCEP data and RAPP reads it as missing? For now I will just pull the changes with interpolation you made earlier.

**Comment by mpaiao** [comment]
@fabeuw If they changed, you can just update the values in modules/mod_ioopts.f90.

**Comment by fabeuw** [comment]
@mpaiao It seemed in fact odd that the reanalyses had so many missing values. I have in fact checked the .nc files using R and I did not find any missing values. I didn't check all the years but the few I have checked didn't have any, while RAPP identifies thousands of missing values. The missing value has changed to -9.96920996838687e+36 so I have tried to input this number in mod_ioopts.f90 and tried also -9.9692100E+36. However I still get these results

```
Loading the NCEP variables...
         [|] Retrieved : air . Range: [  1.9900000E+02 :  3.1610001E+02 ] . # missing:       0.
         [|] Retrieved : pres . Range: [  5.0720000E+04 :  1.0918000E+05 ] . # missing:       0.
         [|] Retrieved : rhum . Range: [  1.0000000E+00 :  1.0000000E+02 ] . # missing:   46458.
         [|] Retrieved : uwnd . Range: [ -3.0699997E+01 :  3.0699997E+01 ] . # missing:    7894.
         [|] Retrieved : vwnd . Range: [ -3.8800003E+01 :  3.6500000E+01 ] . # missing:   10439.
         [|] Retrieved : pres . Range: [  7.7550000E+04 :  1.0301000E+05 ] . # missing:       0.
         [|] Retrieved : dlwrf . Range: [  2.5300000E+02 :  4.8100000E+02 ] . # missing:       0.
         [|] Retrieved : nbdsf . Range: [  1.0000000E+00 :  4.5800000E+02 ] . # missing:   16261.
         [|] Retrieved : nddsf . Range: [  1.0000000E+00 :  3.5100000E+02 ] . # missing:   16821.
         [|] Retrieved : vbdsf . Range: [  1.0000000E+00 :  5.0200000E+02 ] . # missing:   17880.
         [|] Retrieved : vddsf . Range: [  1.0000000E+00 :  5.2500000E+02 ] . # missing:   15270.
         [|] Retrieved : prate . Range: [  9.9884346E-08 :  8.2509988E-04 ] . # missing:       0.
```

For this specific year for example when I check in R there shouldn't be any missing values in rhum, however when just for fun I set misscnt = count(var == 100), it does work correctly. Perhaps it's some problem with the E notation or precision? And now ED is running, I am into 20 years of a simulation.

**Comment by mpaiao** [comment]
@fabeuw I don't think precision or the E notation would make a difference, if anything, these errors would cause RAPP to accept missing values as if they were valid.  Also, the range of valid numbers is reasonable, which suggests that RAPP is reading at least something right. 

I didn't understand the misscnt part, are you saying that the output file worked fine after you changed the value of misscnt at subroutine loadshort?  This is a local variable just for printing stuff on screen, and it shouldn't affect the output files at all.

By the way, just went through the code, and instead of changind ncio_2dshort, I think you could replace the call to ncio_2dshort in subroutine loadshort by ncio_2dvar, which was already available in mod_ncdf_globio.  I don't think this would make any difference, though, because your changes are equivalent.

**Comment by fabeuw** [comment]
I don't know why now the run doesn't crash right away, after the corrections we made the only thing I really did was to extend the cropping area for the data and reduce the edge because my site study was too close to the edge.

@mpaiao I just applied the changes you suggested, now I get 0 missing values. The run crashed on Dec 2003 data after 25 of running no problem, wind speed 'infinite' is the reason. However when I manually checked the h5 file in R and calculated wind speed everything seems fine.
```
> speed=sqrt(u^2+v^2)
> summary(speed)
  Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 0.03341  1.90900  3.02600  3.29500  4.45600 12.10000 
```

i still can't find in ED/src/driver/ED_driver.f90 where speed is calculated. The variable 'vels' is not there neither any comment about wind. At this point I am thinking the calculation of wind speed in ED is having some problems.

**Comment by fabeuw** [comment]
does anybody have an idea why I am running into this issue?

**Comment by mpaiao** [comment]
@fabeuw I don't know why wind speed is becoming infinity, but in any case, wind speed is updated in ED/src/driver/ed_met_driver.f90 (not ed_driver.f90).  There may be some minor calculations in ED/src/utils/lapse.f90 too. 

ED doesn't use wind components, only wind speed, so look for variable vels cgrid%met(ipy)%vels and csite%met(isi)%vels.

**Comment by fabeuw** [comment]
@mpaiao So I have tried to do some debugging. I have added some simple write statements in ed_met_driver.f90 in lines 1688-1713 for the vgrd and ugrd cases, both before and after the code modifies %vels. This is when things star going downhill, %vels becomes NaN and then infinitive. The values of cgrid%met(ipy)%vels are labeled as "before/after do", I am not sure why I am getting these NaN, I have this big value -3.25613740E+36 but that's not in my hdf5 file.

  - Fab ugrd before do:   4.10781860 
  - Fab wnext and wprev:   0.00000000       1.00000000 
  - Fab ugrd(mnext):  -3.25613740E+36
  - Fab ugrd(mprev): -0.594412982  
  - Fab ugrd after do:              NaN
    
  - Fab vgrd before do:   4.10781860    
  - Fab vgrd after do:              NaN
  
  - Fab ugrd before do:   4.10781860    
  - Fab wnext and wprev:   2.77777780E-02  0.972222209    
- Fab ugrd(mnext):  -3.25613740E+36
  - Fab ugrd(mprev): -0.594412982    
- Fab ugrd after do:         Infinity

   - Fab vgrd before do:   4.10781860    
  - Fab vgrd after do:         Infinity

**Comment by mpaiao** [comment]
@fabeuw the ugrd(mnext) is likely to be a variable was not properly initialised.  It's probably worth printing mnext and mnprev as well.  I recommend you to compile a version of ED with very strict debugging settings, this will cause the model to crash at the first violation (division by zero, access of points that haven't been allocated, etc.).

If you are using gfortran:
```Makefile
   F_OPTS= -O0 -ffree-line-length-none -g -fimplicit-none -Wall -finit-real=snan           \
           -ffpe-trap=invalid,zero,overflow,underflow -fcheck=all -frecursive              \
           -fno-whole-file -static
   C_OPTS= -O0 -DLITTLE  -g -static
   LOADER_OPTS= -O0 -ffree-line-length-none -g -fimplicit-none -Wall -finit-real=snan      \
           -ffpe-trap=invalid,zero,overflow,underflow -fcheck=all -frecursive              \
           -fno-whole-file
```

If you are using ifort:
```Makefile
   F_OPTS= -FR -O0 -recursive  -check all -g -debug extended -debug-parameters used        \
           -fpe0 -no-ftz -traceback -ftrapuv -fp-stack-check -implicitnone                 \
           -assume byterecl -static
   C_OPTS= -O0 -DLITTLE  -g -traceback -static
   LOADER_OPTS=-FR -O0 -recursive  -check all -g -debug extended -debug-parameters used    \
               -fpe0 -no-ftz -traceback -ftrapuv -fp-stack-check -implicitnone             \
               -assume byterecl
```

Also, could you post or e-mail your met driver header? My gmail is m d p l o n g o. I just want to make sure it's not something in the instructions.
