### ISSUE TITLE
Error opening site file ...

### ISSUE THREAD

**Issue by Viskari** [EDmodel/ED2#64]
Hello,

 I noticed that with the current as of writing version of ED2, or at least I only noticed it with it, that when I run the ED2 with the pss and css files, it gives initially a warning that it had a problem opening the site file at the location which is exactly the location and the name of the site file and when listing the files with the correct prefix shows the site file in question.

 I am curious have others noticed this problem and how harmful an issue it is?

-- Toni

**Comment by apourmok** [comment]
@Viskari are you talking about this error:
"error opening site file /usr2/postdoc/apourmok/MANDIFORE/MANDIFORE1/sitefiles.lat29.5lon-83.5.site"

If not, could you copy and paste the error here.

**Comment by Viskari** [comment]
Yep, I am talking about that error.

**Comment by apourmok** [comment]
I have the same issue but runs go through. I changed name of the file and
location and everything but still get the same error.

**Comment by Viskari** [comment]
My runs go through as well, but it is something that struck out to me, especially as I am currently struggling with another issue related to ED2 initialization. Just wanted to check if it is something to be alarmed off.

**Comment by apourmok** [comment]
I will let you know if I fix it.

**Comment by apourmok** [comment]
@Viskari do you still get the error?

**Comment by Viskari** [comment]
No, it no longer gives the error message. Not completely certain why not, though.
