### ISSUE TITLE
Running install with the current version causes a problem with disturbance file

### ISSUE THREAD

**Issue by Viskari** [EDmodel/ED2#65]
Hello,

 As I did a pull request and brought my version of ED2, when running install, I got the following error:

disturbance.f90:787.41:

                                    if ( include_pft(ipft) == cpatch%pft(1) ) t
                                         1
Error: Operands of comparison operator '==' at (1) are LOGICAL(4)/INTEGER(4)

Before going in to fix this, I wanted to check if this was due to some issues on my end?

**Comment by Viskari** [comment]
Hello once again,

 After going through the code in more detail, the problem is caused by the following if statement submitted by Markos at the end of last year. Now I can easily get past this problem, but I am checking as I am not completely certain what the if statement is supposed to be checking for as far as I can tell it is only checking the pft against one pft in the patch.


                                    if ( include_pft(ipft) == cpatch%pft(1) ) then
                                       !---------------------------------------------------!
                                       !    PFTs match, send all disturbed area to this    !
                                       ! patch.                                            !
                                       !---------------------------------------------------!
                                       same_pft = .true.
                                       area_fac = act_area_loss(ipa,new_lu)/csite%area(npa)
                                       !---------------------------------------------------!
                                    else
                                       !---------------------------------------------------!
                                       !    PFTs do not match, don't send anything to the  !
                                       ! new patch.                                        !
                                       !---------------------------------------------------!
                                       same_pft = .false.
                                       area_fac = 0.
                                       !---------------------------------------------------!
                                    end if

**Comment by mpaiao** [comment]
@Viskari thanks for catching it, I think it is a typo in the big-leaf version of ED.  I'll double check it tonight, but I _think_ it should be: 
```fortran```
                                if ( ipft == cpatch%pft(1) ) then
                                   !---------------------------------------------------!
                                   !    PFTs match, send all disturbed area to this    !
                                   ! patch.                                            !
                                   !---------------------------------------------------!
                                   same_pft = .true.
                                   area_fac = act_area_loss(ipa,new_lu)/csite%area(npa)
                                   !---------------------------------------------------!
                                else
                                   !---------------------------------------------------!
                                   !    PFTs do not match, don't send anything to the  !
                                   ! new patch.                                        !
                                   !---------------------------------------------------!
                                   same_pft = .false.
                                   area_fac = 0.
                                   !---------------------------------------------------!
                                end if
```

**Comment by mdietze** [comment]
If this is the "big leaf" variant, there is only one cohort.

**Comment by mpaiao** [comment]
I just checked the code again, I think the fix above should be enough.
Toni, since you found the bug, could you please submit a pull request? Thanks.

**Comment by Viskari** [comment]
No problem, just wanted to check it first.

-- Toni

**Comment by apourmok** [comment]
Just pulled in the latest from main line and still get this error. @Viskari did you submit a pull request or should I do it?

**Comment by Viskari** [comment]
The pull request was already submitted a week ago, it just hasn't been
processed yet.

**Comment by mdietze** [comment]
Just did the pull request
