### ISSUE TITLE
Error compiling with gfortran

### ISSUE THREAD

**Issue by robkooper** [EDmodel/ED2#67]
Trying to get the latest version of ED to compile on a Ubuntu VM results in the following error:

```
mpif90 -c -O3 -ffree-line-length-none  -fno-whole-file  -I../../src/include -I/usr/include   -DRAMS_MPI disturbance.f90
disturbance.f90:787.41:

                                    if ( include_pft(ipft) == cpatch%pft(1) ) t
                                         1
Error: Operands of comparison operator '==' at (1) are LOGICAL(4)/INTEGER(4)
```

**Comment by mpaiao** [comment]
Hey @robkooper, this is actually the same problem discussed in  issue #65 / pull request #66. 
For the time being just replace the if statement by if(ipft == cpatch%pft(1)).
