### ISSUE TITLE
RAPP: "No rule to make target `hdf5.mod', needed by `hdf5_coms.o'.  Stop."

### ISSUE THREAD

**Issue by gklarenberg** [EDmodel/ED2#68]
When I try to make the RAPP executable (Mac OS X), I get the above error.

I checked my path in the include.mk file:
"HDF5_INCS=-I/usr/local/hdf5/include"

and this is indeed where hdf5.mod sits. I can't figure out what the issue is. 
I (successfully) installed HDF5 and NetCDF earlier this week, and had to "sudo make" to get it to install, but that does not solve the problem here.
I just (today) got the latest ED / RAPP code from github.

Any ideas?
Thanks - Geraldine

**Comment by gklarenberg** [comment]
I have solved this issue, it requires changes to the generate_deps.sh file. I suspect the file was made for Linux? "sed" does not work properly (the way it's originally written) on my Unix system. I managed to make it work. I don't have much experience with Github - should I send someone the updated code I used?

Also - FYI, NetCDF changed its set-up, the C and Fortran libraries are not installed together. One needs to install the C version first (with shared libraries), then the Fortran version. Might be worth mentioning in the overview pages.
But most importantly: it requires the include.mk file to have 
    NCDF_LIBS=-L/usr/local/lib -lnetcdff -lnetcdf
instead of
    NCDF_LIBS=-L/usr/local/lib -lnetcdf
otherwise it throws strange errors saying "Undefined symbols for architecture x86_64"

**Comment by mpaiao** [comment]
@gklarenberg I think it'd be better if you commit your changes, update your fork on github then submit a pull request. 

Did generate_deps.sh fail only for RAPP?  I'm asking because there are very similar generate_deps.sh in ED/build/bin and BRAMS/build/bin, so we may want to update all of them.

**Comment by robkooper** [comment]
The problem is that sed -i 'query' does not work on the mac, but the -i argument requires an argument. I'll make a pull request for this.

**Comment by fabeuw** [comment]
@gklarenberg @robkooper I have made a comment on this on the pull request, has anybody tested this change in linux? Because I had to revert to the older sed command.

**Comment by robkooper** [comment]
Yes, that is correct there should not have been a space between the -i and the extension on Linux. The mac is OK with the space.

**Comment by robkooper** [comment]
New fix see #115

**Comment by manfredo89** [comment]
@gklarenberg I suspect the undefined symbols might be due to the archive utility. I had a similar issue when trying to build ED on my mac. Here's the discussion #128 . On the other hand I am also having troubles to make rapp. I got the following error
`mod_netcdf.F90(10): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [NETCDF]
   use netcdf
-------^`

Was wondering what part of the generate_deps.sh you changed.

**Comment by gklarenberg** [comment]
@manfredo89 I changed line 8 to:
`sed -i .old 's@[^_]netcdf.mod@ @g' dependency.mk`

See my second message in this discussion too btw, about the change in the include.mk file to get NetCDF libraries.
