### ISSUE TITLE
NetCDF4 causing issues with RAPP code

### ISSUE THREAD

**Issue by gklarenberg** [EDmodel/ED2#70]
The NCEP Reanalysis people have switched their file formats from NetCDF3 to NetCDF4 (http://www.esrl.noaa.gov/psd/data/gridded/netcdf4.html). One of the advantages:
"It also has the advantage that we will not need to pack the data using a scale and offset and users will not need to unpack data."
Which causes trouble with the unpacking part of the code: I get the fatal error that a variable is not a short integer (NF90_SHORT). Indeed, as an example, "ncdump -h air.sig995.1980.nc" tells me that air is a float.

Now - can I just leave out the rescaling in mod_ncdf_globio (lines 1350 to 1358), and of course change line 1333 (xtype /= NF90_SHORT) so it does not throw the fatal error, or are there other places where this could be an issue...?

**Comment by fabeuw** [comment]
@gklarenberg me and @mpaiao have solved this issue, I can upload my changes to my fork and you can use those.

**Comment by gklarenberg** [comment]
@fabeuw @mpaiao Thanks!
