### ISSUE TITLE
ED crashes due to TopModel Hydrology 

### ISSUE THREAD

**Issue by apourmok** [EDmodel/ED2#73]
I get the error message below trying to run the latest version of ED from mainline. I tracked down the error and found out that "signal 8 (SIGFPE): Floating-point exception." error is due to dividing by 0 in lsm_hyd. The value of "cgrid%Te(ipy)" in denominator remains zero. I can fix this by removing assigning a correct values to "cgrid%Te(ipy)" in the formula but want to check out and see if anyone knows why it is there at the first place since I could not understand why. It seems that Te is the terrestrial area in the polygon which is used in hydrology.
(cpoly%moist_tau(isi) = soil(cpoly%ntext_soil(nzg-1,isi))%slmsts / & 
                   (MoistRateTuning*cpoly%moist_f(isi)*cgrid%Te(ipy)* &
                   exp(MoistRateTuning*cpoly%moist_f(isi)*min(0.0,cgrid%zbar(ipy))) & 
                   *exp(cgrid%wbar(ipy))*fracliqtotal)

--------------------------------------------------------------------------------------------------------------------
 === Time integration starts (model) ===
 - Simulating:   06/01/2000 00:00:00 UTC

Program received signal 8 (SIGFPE): Floating-point exception.

Backtrace for this error:
  + /lib64/libc.so.6(+0x326a0) [0x2af5500c26a0]
  + function calchydrosubsurface_ (0xA4433C)
    at line 391 of file lsm_hyd.f90
  + function ed_model_ (0x512C0B)
    at line 489 of file ed_model.F90
  + function ed_driver_ (0x434C99)
    at line 297 of file ed_driver.F90
  + in the main program
    at line 285 of file edmain.F90
  + /lib64/libc.so.6(__libc_start_main+0xfd) [0x2af5500aed5d]
** Warning: a core dump was requested, but the core sizelimit
**          is currently zero.

Quit

**Comment by apourmok** [comment]
Fixed the bug so I am going to close this. Will submit a pull request after I cherry pick my commit.

**Comment by mdietze** [comment]
Te needs to be there for the hydrology to work so don't remove it and don't set it to 1. It's not the area, but the area weighted mean of T0. T0 is the soil conductivity divided by the depth decay rate of conductivity. @apourmok what's your settings file look like? Looking at the init code it appears that Te would stay zero if there's 0 sites, so we should probably add a check to init_hydro_sites.f90 so that it throws an error immediately if nsites <= 0

**Comment by apourmok** [comment]
I did not remove it or set it 1. I have 1 site in all my runs. 
I fixed it by adding few lines below which is basically from ed_init.F90:

              sc = cpoly%ntext_soil(nzg-1,isi)
              K0 = soil(sc)%slcons0
              T0 = K0/cpoly%moist_f(isi)
              Te = Te + T0*cpoly%area(isi)
              area_sum = area_sum + dble(cpoly%area(isi))
              Te = Te/real(area_sum)
              cgrid%Te(ipy) = Te

**Comment by apourmok** [comment]
Since the bug is fixed and the pull request is merged, I am closing this issue.
