### ISSUE TITLE
Occasional issues with water surface temperature in late summer

### ISSUE THREAD

**Issue by Viskari** [EDmodel/ED2#82]
While running an ensemble, a few members of the ensemble crash because of the seemingly eternal issue with the surface water temperature. The error message is below and in all cases it happens in July/August:

  STEPSIZE UNDERFLOW IN EULER_INT
--------------------------------------------------------------------------------
 + LONGITUDE:       -79.500000
 + LATITUDE:         35.500000
 + PATCH INFO:
   - NUMBER:            7
   - AGE:            7.6917E+01
   - DIST_TYPE:         5
 + MINSTEP:        T
 + STUCK:          F
 + ERRMAX:           1.0000E+01
 + X:                0.0000E+00
 + H:                6.9742E-08
 + OLDH:             1.3780E-07
 + NEWH:             6.9742E-08
 + SAFETY:           9.0000E-01
--------------------------------------------------------------------------------
   Likely to be a rejected step problem.
================================================================================
========================================
 + Snow/pond temperature is off...
----------------------------------------
 This layer:          1
 # of layers:         1
 Stability flag:      2
 SFCW_TEMP:           99.7261
 SFCW_ENERGY:    1111720.4992
 SFCW_MASS:            5.3262
 SFCW_DEPTH:           0.0053
 D(SFCW_E)/Dt:       169.2912
 D(SFCW_M)/Dt:         0.0000
========================================

As said, it only happens with a few ensemble members, but it is causing some issues with the system. I wanted to check if anyone else has ran in to this problem and if there are any ideas on how to deal with it?

Additional thing is that I've actually ran the ensemble without difficulties before the fixes in the thermal libraries, so this does seem to be resulting from them.

**Comment by apourmok** [comment]
I had/have the same issue but lowering the integration time step or lowering the rk4_tolerance solved my issue and the only downside it longer run time.

**Comment by Viskari** [comment]
Thanks, this seemed to fix the problem.
